version: 2.1

orbs:
  # The python orb contains a set of prepackaged CircleCI configuration you can use repeatedly in your configuration files
  # Orb commands and jobs help you with common scripting around a language/tool
  # so you dont have to copy and paste it everywhere.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@1.5.0

jobs:
  build-and-test:

    # Primary container image where all commands run

    docker:
      - image: cimg/python:3.8.10
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          APP_SETTINGS: testing
          REDIS_URL: "redis://localhost:6379"
          HEROKU_POSTGRESQL_AQUA_URL: "None"
          DATABASE_URL: "None"
          TEST_DATABASE_URL: postgresql://root@localhost/circle_test

          AVIV: "REVER MWIMUTO LIMITE"
          TARGET: "lasshous"
          INDEX: "agentindex.html"
          STAGING: "True"

          CLOUDINARY_URL: "cloudinary://597783923547314:uoZkQ1VBpnG8nJbOCJ_TWieviMs@dmq9pwyon"

          G_ACCOUNT_ALERTS: "notifications.kiotapay@gmail.com"
          G_ACCOUNT: "kiotapay@gmail.com"
          G_PASS: "mnswpjyxdcvzbjes"

          SENDER_ID: "KIOTAPAY"
          SMS_API_KEY: "4f501cae150c2bf1ac987dc89d8a724aedbea5b6d248dd3790c4ee7da421c957"
          SMS_USERNAME: "eapartment"

    # Service container image

      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: postgres

    steps:
      - checkout

      - python/install-packages:
          pkg-manager: pip
          # app-dir: ~/project/package-directory/  # If you're requirements.txt isn't in the root directory.
          # pip-dependency-file: test-requirements.txt  # if you have a different name for your requirements file, maybe one that combines your runtime and test requirements.
      - run:
          name: Run tests
          # This assumes pytest is installed via the install-package step above
          command: pytest

      # - run: sudo apt-get update
      # - run: sudo apt-get install postgresql-client-12
      # - run: whoami
      # - run: |
      #     psql \
      #     -d $TEST_DATABASE_URL \
      #     -c "CREATE TABLE test (name char(25));"
      # - run: |
      #     psql \
      #     -d $TEST_DATABASE_URL \
      #     -c "INSERT INTO test VALUES ('John'), ('Joanna'), ('Jennifer');"
      # - run: |
      #     psql \
      #     -d $TEST_DATABASE_URL \
      #     -c "SELECT * from test"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test