from flask_restful import Api
from flask import Blueprint

from .views.apartment_management import *
from .views.user_management import *
from .views.billing import *
from .reports.reports import *
from .views.admin_views import *
# from .views.contact import *

version_one = Blueprint('api', __name__)
api = Api(version_one)

api.add_resource(DataUpload,"/data/upload")

api.add_resource(LandingPage,"/")
api.add_resource(DbInitializer,"/restricted")
api.add_resource(RegisterUserGroup,"/add/usergroup")
api.add_resource(DeleteUserGroup,"/remove/usergroup")
api.add_resource(Users,"/users")
api.add_resource(RegisterUser,"/add/user")
api.add_resource(SignUpCategory,"/signup")
api.add_resource(RequestDemo,"/request/demo")
api.add_resource(SelfUserRegisterAgent,"/signup/agent")
api.add_resource(SelfUserRegisterOwner,"/signup/owner")
api.add_resource(AdminRegisterUser,"/add/admincreateuser")
api.add_resource(ViewNewClients,"/new/clients")
api.add_resource(ViewClients,"/clients")
api.add_resource(AdminCreateAgent,"/add/admincreateagent")
api.add_resource(Index,"/index")
api.add_resource(MonitorActivity,"/monitor/activity")
api.add_resource(PropData,"/fetch/propdata")
api.add_resource(PropSearchData,"/fetch/searchdata")
api.add_resource(PropStats,"/fetch/propstats")
api.add_resource(HouseStats,"/fetch/housestats")
api.add_resource(GraphStats,"/fetch/graphstats")
api.add_resource(ComStats,"/fetch/comstats")
api.add_resource(ComGraphStats,"/fetch/comgraphstats")
api.add_resource(UserLogin,"/signin")
api.add_resource(UserLogout,"/logout")
api.add_resource(DeleteUser,"/remove/user")
api.add_resource(UpdateUser,"/update/user")
api.add_resource(AssignRole,"/assign/role")
api.add_resource(ModifyAccessRight,"/modify/access")

api.add_resource(CreateLocation,"/add/location")
api.add_resource(RegisterOwner,"/add/owner")
api.add_resource(CreateApartment,"/add/apartment")
api.add_resource(Bills,"/bills")
api.add_resource(DiscardBills,"/discard/bills")
api.add_resource(Payments,"/all/payments")
api.add_resource(PropertyManagement,"/manage/property")
api.add_resource(MeterManagement,"/meters")
api.add_resource(SubmissionsManagement,"/submissions")
api.add_resource(PaymentsManagement,"/manage/payments")
api.add_resource(UpdateCompanyDetails,"/update/companyinfo")
api.add_resource(PropertyImageChange,"/change/prop/image")
api.add_resource(UpdatePropertyDetails,"/update/propinfo")
api.add_resource(PropertyAccess,"/property/access")
api.add_resource(PropertyAccessTermination,"/property/termination")
api.add_resource(Expenses,"/expenses")
api.add_resource(ExpenseManagement,"/expense/management")

api.add_resource(BulkSms,"/bulk/sms")
api.add_resource(FetchSentSms,"/fetch/sentsms")
api.add_resource(SendInvoices,"/send/invoices")
api.add_resource(SendMail,"/send/mail")
api.add_resource(SendSms,"/send/sms")
api.add_resource(TenantSms, "/tenant/sms")
api.add_resource(CreateHouseCode,"/create/housecode")
api.add_resource(EditHouseCode,"/edit/housecode")
api.add_resource(CreateHouse, "/add/house")
api.add_resource(EditHouse, "/edit/house")
api.add_resource(HouseBillStatus, "/bill/status")
api.add_resource(TenantSmsStatus, "/sms/status")
api.add_resource(SmsDelivery, "/sms/delivery")
api.add_resource(CreateMeter, "/add/meter")
api.add_resource(UpdateMeter,"/edit/meter")
api.add_resource(AllocateMeters,"/allocate/meter")
api.add_resource(MeterRemoval,"/clear/meter")

# api.add_resource(StandardRates,"/create/standardrates")
api.add_resource(CaptureReading, "/readings")
api.add_resource(CreateWaterCharge, "/create/waterbills")
api.add_resource(EditReading,"/edit/readings")
api.add_resource(TenantHouseRequest,"/tenant/request")
api.add_resource(HouseClearanceRequest,"/clear/request")
api.add_resource(HouseTransferRequest,"/transfer/request")
api.add_resource(ContactManagement,"/tenant/message")
api.add_resource(HandleTenantRequest,"/handle/request")
api.add_resource(ReactToRequest,"/request/respond")
api.add_resource(TrackRequest,"/track/request")
api.add_resource(DeleteRequest,"/delete/request")
api.add_resource(AddTenant,"/add/tenant")
api.add_resource(TenantManagement,"/tenants")
api.add_resource(UpdateTenant,"/update/tenant")
api.add_resource(AllocateTenants,"/allocate/tenant")
api.add_resource(TenantClearance,"/clear/tenant")
api.add_resource(TenantUserSignUpStageOne,"/tenant/signup")
api.add_resource(TenantUserSignUpStageTwo,"/tenant/signuptwo")
api.add_resource(CheckVacancy,"/search/house")

api.add_resource(Settings, "/settings")
api.add_resource(Search, "/search")


api.add_resource(Results, "/results")


api.add_resource(Billing, "/billing")
api.add_resource(BillProgress, "/bill/progress")
api.add_resource(SwitchPeriod,"/switch")
api.add_resource(Replenish,"/replenish")
api.add_resource(ClientBilling,"/client/billing")
api.add_resource(SetReminder,"/set/reminder")
api.add_resource(AmendCharge,"/amend/charge")
api.add_resource(EditBill,"/edit/bill")
api.add_resource(EditSummary,"/edit/summary")
api.add_resource(ReceivePayment,"/receive/payment")
api.add_resource(ReceiveDepositPayment,"/deposit/payment")
api.add_resource(TenantPayment,"/tenant/payment")
api.add_resource(StkCallBackUrlProminance,"/datareceive")
api.add_resource(StkCallBackUrlKiotapay,"/kiotapay/datareceive")
api.add_resource(ResultUrl,"/getdata/<int:shortcode>")
api.add_resource(TestApi,"/testapi")
api.add_resource(QueryMpesaTrans,"/query")
api.add_resource(ConsumeMpesaData,"/mpesa/payment")
api.add_resource(ResetAllMpesaData,"/restricted/datareset")

#c2b urls
api.add_resource(CallBackUrlProminance,"/promitech/payment")
api.add_resource(CallBackUrlKiotapay,"/kiotapay/payment")
api.add_resource(CallBackUrlLatitude,"/latitude/payment")
api.add_resource(CallBackUrlPremier,"/premier/payment")
api.add_resource(CallBackUrlPremierRealty,"/prealty/payment")

#bank urls
api.add_resource(CallBackUrlEquity,"/nest/payment")
api.add_resource(CallBackUrlEquityProd,"/promitech/4012401")

api.add_resource(CallBackUrlLes,"/les/45")
api.add_resource(CallBackUrlTestLes,"/test/les/45")

api.add_resource(ViewHouses, "/view/houses")
api.add_resource(ViewMeters, "/view/meters")

api.add_resource(ViewBookings, "/view/bookings")
api.add_resource(ViewTenancy, "/view/tenancy")
api.add_resource(ViewTenantInfo,"/view/tenantinfo")
api.add_resource(ViewTenantDetail, "/view/tenantdetail")
api.add_resource(ViewTenantDetailTwo,"/view/tenantdetailtwo")
api.add_resource(ViewVacatedTenants, "/view/vacatedtenants")

api.add_resource(ViewMonthlyReading, "/view/monthlyreadings")
api.add_resource(ViewWaterCharge, "/view/watercharge")
api.add_resource(ViewPayment, "/view/payments")
api.add_resource(ViewMonthlyPayments,"/view/monthlypayment")

api.add_resource(GetStarted,"/get/started")
api.add_resource(ContactUs,"/contact")
api.add_resource(Features,"/features")
api.add_resource(AboutUs,"/about/us")
api.add_resource(Pricing,"/pricing")
api.add_resource(ReportBug,"/report/bug")
api.add_resource(ViewBugs, "/view/bugs")

api.add_resource(Invoice,"/invoice")
api.add_resource(BillInvoice,"/bill/invoice")
api.add_resource(ClientInvoice,"/client/invoice")
api.add_resource(MyPayments,"/payments")
api.add_resource(Receipt,"/receipt")
api.add_resource(UpdateBalance,"/update/balance")
api.add_resource(EditPayment,"/edit/payment")

api.add_resource(Reports,"/reports")
api.add_resource(Balances,"/balances")
api.add_resource(RentReport,"/rent/report")
api.add_resource(MonthlyStatement,"/monthly/statement")
api.add_resource(SummarisedCombinedBill,"/summarised/combinedbill")
api.add_resource(ExternalDetail,"/external/detailed")
api.add_resource(LandlordProfitAndLossSummary,"/landlord/summary")
api.add_resource(LandlordProfitAndLoss,"/landlord/pl")
api.add_resource(RentStatement,"/rent/statement")
api.add_resource(WaterStatement,"/water/statement")
api.add_resource(ListedProperties,"/listed/properties")
api.add_resource(GarbageStatement,"/garbage/statement")
api.add_resource(InternalSummary,"/internal/summarised")
api.add_resource(InternalDetail,"/internal/detailed")
api.add_resource(InternalDetailAlt,"/general/statement")
api.add_resource(TenantStatement,"/tenant/statement")
api.add_resource(TenantStatementTwo,"/tenant/statement2")
api.add_resource(TenantStatementThree,"/tenant/statement3")

api.add_resource(CollectionRatioReport,"/cr/report")
api.add_resource(ManagementFeeReport,"/commission/report")
api.add_resource(TenantDeposit,"/deposit/report")
api.add_resource(OfficePnL,"/profitnloss/report")
api.add_resource(OfficeExpenses,"/office/expenses")



api.add_resource(ExpenseDetail,"/expenses/detailed")
api.add_resource(SubmissionsReport,"/submissions/report")

api.add_resource(ArrearsComparison,"/arrears")
api.add_resource(PaymentsComparison,"/compare/payments")

api.add_resource(FetchTenants,"/fetch/tenants")
api.add_resource(FetchHouses,"/fetch/houses")
api.add_resource(FetchRates,"/fetch/rates")
api.add_resource(FetchMeters,"/fetch/meters")
api.add_resource(FetchReadings,"/fetch/readings")
api.add_resource(FetchPayments,"/fetch/payments")
api.add_resource(FetchSubmissions,"/fetch/submissions")
api.add_resource(FetchBills,"/fetch/bills")

api.add_resource(Privacy,"/privacy")

# ADMIN ROUTES
api.add_resource(AllProperties,"/all/properties")
api.add_resource(AddProp,"/add/prop")
api.add_resource(AddOwner,"/add/propowner")
api.add_resource(AllOwners,"/all/owners")
api.add_resource(AddRegion,"/add/region")
api.add_resource(LinkProperty,"/link/prop")
api.add_resource(EditProp,"/edit/prop")
api.add_resource(LandlordDemoLogin,"/demo/kp0716674695mp0725538750landlord")
api.add_resource(TenantDemoLogin,"/demo/kp0716674695mp0725538750tenant")
api.add_resource(DemoAccess,"/trial/<string:ri>")
api.add_resource(Demo,"/demo")


# api.add_resource(Robots,"/robots")
api.add_resource(Robots,"/robots.txt")
api.add_resource(ViewReceipt,"/r/<string:ri>")
api.add_resource(UserActivation,"/user/<string:ri>")

api.add_resource(DownloadReceipt,"/download/receipt/<string:ri>")
api.add_resource(DownloadInvoice,"/download/invoice/<string:ri>")
api.add_resource(DeleteReceipt,"/del/r/prop/<string:propid>")

api.add_resource(DownloadTemplate,"/download/template/<string:file>")
