"""empty message

Revision ID: 004e8c1c0b9b
Revises: 1a3d1cd21b83
Create Date: 2026-03-20 14:01:16.142277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004e8c1c0b9b'
down_revision = '1a3d1cd21b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housecodes', sa.Column('eleccharge', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('housecodes', 'eleccharge')
    # ### end Alembic commands ###
