"""empty message

Revision ID: 012948eee420
Revises: b633a47db697
Create Date: 2023-04-01 18:06:47.817140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012948eee420'
down_revision = 'b633a47db697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthlycharges', sa.Column('paidll', sa.Float(), nullable=True))
    op.add_column('occupancy', sa.Column('days', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('occupancy', 'days')
    op.drop_column('monthlycharges', 'paidll')
    # ### end Alembic commands ###
