"""empty message

Revision ID: 044b5ff8a3b0
Revises: 0d493768e79f
Create Date: 2022-10-26 20:13:32.018187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '044b5ff8a3b0'
down_revision = '0d493768e79f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paymentschedules', sa.Column('rbalance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paymentschedules', 'rbalance')
    # ### end Alembic commands ###
