"""empty message

Revision ID: 05c651e2f014
Revises: 34b26b9f6b14
Create Date: 2022-05-15 14:30:08.840073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c651e2f014'
down_revision = '34b26b9f6b14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permanenttenants', sa.Column('contracts_url', sa.VARCHAR(), nullable=True))
    op.add_column('permanenttenants', sa.Column('deposit', sa.Float(), nullable=True))
    op.add_column('permanenttenants', sa.Column('instalment', sa.Float(), nullable=True))
    op.add_column('permanenttenants', sa.Column('negotiated_price', sa.Float(), nullable=True))
    op.add_column('permanenttenants', sa.Column('num_instalment', sa.Float(), nullable=True))
    op.add_column('permanenttenants', sa.Column('plan', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permanenttenants', 'plan')
    op.drop_column('permanenttenants', 'num_instalment')
    op.drop_column('permanenttenants', 'negotiated_price')
    op.drop_column('permanenttenants', 'instalment')
    op.drop_column('permanenttenants', 'deposit')
    op.drop_column('permanenttenants', 'contracts_url')
    # ### end Alembic commands ###
