"""empty message

Revision ID: 0921dd5bc976
Revises: 5e8be399d9ec
Create Date: 2022-09-05 14:31:28.452068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0921dd5bc976'
down_revision = '5e8be399d9ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('ctype', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'ctype')
    # ### end Alembic commands ###
