"""empty message

Revision ID: 0976650b5bae
Revises: 925e1609c2ff
Create Date: 2021-02-08 19:21:17.183521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0976650b5bae'
down_revision = '925e1609c2ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('billing_period', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'billing_period')
    # ### end Alembic commands ###
