"""empty message

Revision ID: 0aacc785b7a0
Revises: c32df49d89fb
Create Date: 2022-07-04 15:30:26.587791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aacc785b7a0'
down_revision = 'c32df49d89fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthlycharges', sa.Column('booking', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('booking_balance', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('booking_due', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('booking_paid', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('instalment', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('instalment_balance', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('instalment_due', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('instalment_paid', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monthlycharges', 'instalment_paid')
    op.drop_column('monthlycharges', 'instalment_due')
    op.drop_column('monthlycharges', 'instalment_balance')
    op.drop_column('monthlycharges', 'instalment')
    op.drop_column('monthlycharges', 'booking_paid')
    op.drop_column('monthlycharges', 'booking_due')
    op.drop_column('monthlycharges', 'booking_balance')
    op.drop_column('monthlycharges', 'booking')
    # ### end Alembic commands ###
