"""empty message

Revision ID: 0c8b147ad0c0
Revises: 36dce0a4b1db
Create Date: 2021-04-01 10:25:31.514474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8b147ad0c0'
down_revision = '36dce0a4b1db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('electricityreadings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('reading_period', sa.DateTime(), nullable=True),
    sa.Column('reading', sa.Integer(), nullable=True),
    sa.Column('last_reading', sa.Integer(), nullable=True),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('charged', sa.Boolean(), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.Column('meter_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.ForeignKeyConstraint(['meter_id'], ['meters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('meters', sa.Column('metertype', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meters', 'metertype')
    op.drop_table('electricityreadings')
    # ### end Alembic commands ###
