"""empty message

Revision ID: 0d493768e79f
Revises: 6d326ec09c8a
Create Date: 2022-10-26 19:20:04.128667

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0d493768e79f'
down_revision = '6d326ec09c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paymentschedules', 'rbalance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paymentschedules', sa.Column('rbalance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
