"""empty message

Revision ID: 0ed25f57dc84
Revises: 9a08d0b49fa2
Create Date: 2022-06-20 16:13:13.643592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ed25f57dc84'
down_revision = '9a08d0b49fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landlordremittances', sa.Column('deposit', sa.Float(), nullable=True))
    op.drop_column('landlordremittances', 'utilities_paid')
    op.drop_column('landlordremittances', 'rent_paid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landlordremittances', sa.Column('rent_paid', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('landlordremittances', sa.Column('utilities_paid', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('landlordremittances', 'deposit')
    # ### end Alembic commands ###
