"""empty message

Revision ID: 0f96cfde67b9
Revises: 39d641b060fc
Create Date: 2022-07-14 04:55:42.829708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f96cfde67b9'
down_revision = '39d641b060fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housecodes', sa.Column('commission', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('housecodes', 'commission')
    # ### end Alembic commands ###
