"""empty message

Revision ID: 1006242dad87
Revises: 987ea5a3ce93
Create Date: 2025-02-24 11:00:02.768265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1006242dad87'
down_revision = '987ea5a3ce93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenantdeposits', sa.Column('account', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenantdeposits', 'account')
    # ### end Alembic commands ###
