"""empty message

Revision ID: 101305ed5d84
Revises: 5b3f6504d04f
Create Date: 2025-09-04 21:49:32.593114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '101305ed5d84'
down_revision = '5b3f6504d04f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_transactions', sa.Column('quantityy', sa.Float(), nullable=True))
    op.drop_column('stock_transactions', 'quantity')
    op.add_column('stocksales', sa.Column('quantityy', sa.Float(), nullable=True))
    op.drop_column('stocksales', 'quantity')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocksales', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('stocksales', 'quantityy')
    op.add_column('stock_transactions', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('stock_transactions', 'quantityy')
    # ### end Alembic commands ###
