"""empty message

Revision ID: 107344a9e5be
Revises: e417db891397
Create Date: 2021-11-07 20:54:04.690989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '107344a9e5be'
down_revision = 'e417db891397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('billprogress', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'billprogress')
    # ### end Alembic commands ###
