"""empty message

Revision ID: 10c10181b71f
Revises: ecddc9db3d47
Create Date: 2020-12-14 18:19:22.474500

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10c10181b71f'
down_revision = 'ecddc9db3d47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('housecodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codename', sa.String(), nullable=True),
    sa.Column('rentrate', sa.Float(), nullable=True),
    sa.Column('waterrate', sa.Float(), nullable=True),
    sa.Column('securityrate', sa.Float(), nullable=True),
    sa.Column('garbagerate', sa.Float(), nullable=True),
    sa.Column('finerate', sa.Float(), nullable=True),
    sa.Column('charge_type_id', sa.Integer(), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ),
    sa.ForeignKeyConstraint(['charge_type_id'], ['chargetypes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('chargedescriptions')
    op.add_column('houses', sa.Column('housecode_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'houses', 'housecodes', ['housecode_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'houses', type_='foreignkey')
    op.drop_column('houses', 'housecode_id')
    op.create_table('chargedescriptions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('charge_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('apartment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('house_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], name='chargedescriptions_apartment_id_fkey'),
    sa.ForeignKeyConstraint(['charge_type_id'], ['chargetypes.id'], name='chargedescriptions_charge_type_id_fkey'),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], name='chargedescriptions_house_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='chargedescriptions_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chargedescriptions_pkey')
    )
    op.drop_table('housecodes')
    # ### end Alembic commands ###
