"""empty message

Revision ID: 113e5b6823a7
Revises: fbca1ffe873d
Create Date: 2025-12-17 11:53:34.288142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '113e5b6823a7'
down_revision = 'fbca1ffe873d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_transactions', sa.Column('transaction_category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_transactions', 'transaction_category')
    # ### end Alembic commands ###
