"""empty message

Revision ID: 115587a62090
Revises: 6b3701357315
Create Date: 2022-05-11 12:18:16.360012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115587a62090'
down_revision = '6b3701357315'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housecodes', sa.Column('agreementrate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('housecodes', 'agreementrate')
    # ### end Alembic commands ###
