"""empty message

Revision ID: 11cac1d24ceb
Revises: d588a9ceb6e7
Create Date: 2021-07-06 23:47:04.188707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11cac1d24ceb'
down_revision = 'd588a9ceb6e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('subscription', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'subscription')
    # ### end Alembic commands ###
