"""empty message

Revision ID: 155573d2c301
Revises: 107344a9e5be
Create Date: 2021-11-23 02:36:03.274313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155573d2c301'
down_revision = '107344a9e5be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthlycharges', sa.Column('agreement_balance', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('agreement_paid', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('deposit_balance', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('deposit_paid', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('electricity_balance', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('electricity_paid', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('garbage_balance', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('garbage_paid', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('maintenance_balance', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('maintenance_paid', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('penalty_balance', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('penalty_paid', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('rent_balance', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('rent_paid', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('security_balance', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('security_paid', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('updated', sa.Boolean(), nullable=True))
    op.add_column('monthlycharges', sa.Column('water_balance', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('water_paid', sa.Float(), nullable=True))
    op.add_column('payments', sa.Column('agreement_paid', sa.Float(), nullable=True))
    op.add_column('payments', sa.Column('deposit_paid', sa.Float(), nullable=True))
    op.add_column('payments', sa.Column('electricity_paid', sa.Float(), nullable=True))
    op.add_column('payments', sa.Column('garbage_paid', sa.Float(), nullable=True))
    op.add_column('payments', sa.Column('maintenance_paid', sa.Float(), nullable=True))
    op.add_column('payments', sa.Column('penalty_paid', sa.Float(), nullable=True))
    op.add_column('payments', sa.Column('rent_paid', sa.Float(), nullable=True))
    op.add_column('payments', sa.Column('security_paid', sa.Float(), nullable=True))
    op.add_column('payments', sa.Column('water_paid', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'water_paid')
    op.drop_column('payments', 'security_paid')
    op.drop_column('payments', 'rent_paid')
    op.drop_column('payments', 'penalty_paid')
    op.drop_column('payments', 'maintenance_paid')
    op.drop_column('payments', 'garbage_paid')
    op.drop_column('payments', 'electricity_paid')
    op.drop_column('payments', 'deposit_paid')
    op.drop_column('payments', 'agreement_paid')
    op.drop_column('monthlycharges', 'water_paid')
    op.drop_column('monthlycharges', 'water_balance')
    op.drop_column('monthlycharges', 'updated')
    op.drop_column('monthlycharges', 'security_paid')
    op.drop_column('monthlycharges', 'security_balance')
    op.drop_column('monthlycharges', 'rent_paid')
    op.drop_column('monthlycharges', 'rent_balance')
    op.drop_column('monthlycharges', 'penalty_paid')
    op.drop_column('monthlycharges', 'penalty_balance')
    op.drop_column('monthlycharges', 'maintenance_paid')
    op.drop_column('monthlycharges', 'maintenance_balance')
    op.drop_column('monthlycharges', 'garbage_paid')
    op.drop_column('monthlycharges', 'garbage_balance')
    op.drop_column('monthlycharges', 'electricity_paid')
    op.drop_column('monthlycharges', 'electricity_balance')
    op.drop_column('monthlycharges', 'deposit_paid')
    op.drop_column('monthlycharges', 'deposit_balance')
    op.drop_column('monthlycharges', 'agreement_paid')
    op.drop_column('monthlycharges', 'agreement_balance')
    # ### end Alembic commands ###
