"""empty message

Revision ID: 19084f107280
Revises: 216755daf299
Create Date: 2021-01-18 19:04:22.387909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19084f107280'
down_revision = '216755daf299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('internalexpenses', 'toggle')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internalexpenses', sa.Column('toggle', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
