"""empty message

Revision ID: 1a3d1cd21b83
Revises: 7a23bb65523b
Create Date: 2026-03-19 11:41:32.453607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3d1cd21b83'
down_revision = '7a23bb65523b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_transactions', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_transactions', 'is_deleted')
    # ### end Alembic commands ###
