"""empty message

Revision ID: 1bc570b3c82b
Revises: e2139007d52c
Create Date: 2022-01-07 12:37:19.171654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc570b3c82b'
down_revision = 'e2139007d52c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housecodes', sa.Column('waterrate1', sa.Float(), nullable=True))
    op.add_column('housecodes', sa.Column('waterrate2', sa.Float(), nullable=True))
    op.add_column('housecodes', sa.Column('waterrate3', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('housecodes', 'waterrate3')
    op.drop_column('housecodes', 'waterrate2')
    op.drop_column('housecodes', 'waterrate1')
    # ### end Alembic commands ###
