"""empty message

Revision ID: 1c5523b849a9
Revises: 6255d5276afa
Create Date: 2021-03-10 09:31:37.354808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c5523b849a9'
down_revision = '6255d5276afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occupancy', sa.Column('vacate_period', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('occupancy', 'vacate_period')
    # ### end Alembic commands ###
