"""empty message

Revision ID: 1dc3d3dcfc3a
Revises: ea8f9fef257d
Create Date: 2024-06-08 00:02:03.761351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc3d3dcfc3a'
down_revision = 'ea8f9fef257d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stocks', 'added_stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stocks', 'added_stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
