"""empty message

Revision ID: 1e4f6f48a9c9
Revises: f26c5ef2f192
Create Date: 2023-09-09 12:35:54.141363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e4f6f48a9c9'
down_revision = 'f26c5ef2f192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenantexpenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repainting', sa.Float(), nullable=True),
    sa.Column('plumbing', sa.Float(), nullable=True),
    sa.Column('electricals', sa.Float(), nullable=True),
    sa.Column('fixtures', sa.Float(), nullable=True),
    sa.Column('others', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('paid', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('modifiedon', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('ptenant_id', sa.Integer(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.ForeignKeyConstraint(['ptenant_id'], ['permanenttenants.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenantexpenses')
    # ### end Alembic commands ###
