"""empty message

Revision ID: 1feffcc9edbd
Revises: 7b9ba58efbcf
Create Date: 2025-07-11 03:54:43.898391

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1feffcc9edbd'
down_revision = '7b9ba58efbcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthlychargehistories', sa.Column('createdon', sa.DateTime(), nullable=True))
    op.drop_constraint('monthlychargehistories_user_id_fkey', 'monthlychargehistories', type_='foreignkey')
    op.drop_constraint('monthlychargehistories_apartment_id_fkey', 'monthlychargehistories', type_='foreignkey')
    op.drop_constraint('monthlychargehistories_modifiedby_fkey', 'monthlychargehistories', type_='foreignkey')
    op.drop_constraint('monthlychargehistories_house_id_fkey', 'monthlychargehistories', type_='foreignkey')
    op.drop_constraint('monthlychargehistories_ptenant_id_fkey', 'monthlychargehistories', type_='foreignkey')
    op.drop_constraint('monthlychargehistories_tenant_id_fkey', 'monthlychargehistories', type_='foreignkey')
    op.drop_column('monthlychargehistories', 'smsid')
    op.drop_column('monthlychargehistories', 'fine_date')
    op.drop_column('monthlychargehistories', 'invoice_date')
    op.drop_column('monthlychargehistories', 'user_id')
    op.drop_column('monthlychargehistories', 'pay_date')
    op.drop_column('monthlychargehistories', 'tenant_id')
    op.drop_column('monthlychargehistories', 'sms_invoice')
    op.drop_column('monthlychargehistories', 'updated')
    op.drop_column('monthlychargehistories', 'apartment_id')
    op.drop_column('monthlychargehistories', 'email_invoice')
    op.drop_column('monthlychargehistories', 'paidll')
    op.drop_column('monthlychargehistories', 'house_id')
    op.drop_column('monthlychargehistories', 'modifiedby')
    op.drop_column('monthlychargehistories', 'date')
    op.drop_column('monthlychargehistories', 'dep_journal')
    op.drop_column('monthlychargehistories', 'arrears_updated')
    op.drop_column('monthlychargehistories', 'fine_status')
    op.drop_column('monthlychargehistories', 'modifiedon')
    op.drop_column('monthlychargehistories', 'ptenant_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthlychargehistories', sa.Column('ptenant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('monthlychargehistories', sa.Column('modifiedon', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('monthlychargehistories', sa.Column('fine_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('monthlychargehistories', sa.Column('arrears_updated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('monthlychargehistories', sa.Column('dep_journal', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('monthlychargehistories', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('monthlychargehistories', sa.Column('modifiedby', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('monthlychargehistories', sa.Column('house_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('monthlychargehistories', sa.Column('paidll', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('monthlychargehistories', sa.Column('email_invoice', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('monthlychargehistories', sa.Column('apartment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('monthlychargehistories', sa.Column('updated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('monthlychargehistories', sa.Column('sms_invoice', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('monthlychargehistories', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('monthlychargehistories', sa.Column('pay_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('monthlychargehistories', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('monthlychargehistories', sa.Column('invoice_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('monthlychargehistories', sa.Column('fine_date', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('monthlychargehistories', sa.Column('smsid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('monthlychargehistories_tenant_id_fkey', 'monthlychargehistories', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key('monthlychargehistories_ptenant_id_fkey', 'monthlychargehistories', 'permanenttenants', ['ptenant_id'], ['id'])
    op.create_foreign_key('monthlychargehistories_house_id_fkey', 'monthlychargehistories', 'houses', ['house_id'], ['id'])
    op.create_foreign_key('monthlychargehistories_modifiedby_fkey', 'monthlychargehistories', 'users', ['modifiedby'], ['id'])
    op.create_foreign_key('monthlychargehistories_apartment_id_fkey', 'monthlychargehistories', 'apartments', ['apartment_id'], ['id'])
    op.create_foreign_key('monthlychargehistories_user_id_fkey', 'monthlychargehistories', 'users', ['user_id'], ['id'])
    op.drop_column('monthlychargehistories', 'createdon')
    # ### end Alembic commands ###
