"""empty message

Revision ID: 216755daf299
Revises: 258982cd01b5
Create Date: 2021-01-18 06:53:05.367269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216755daf299'
down_revision = '258982cd01b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internalexpenses', sa.Column('toggle', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('internalexpenses', 'toggle')
    # ### end Alembic commands ###
