"""empty message

Revision ID: 21fd64c94ab2
Revises: fd13519f15d0
Create Date: 2022-04-07 06:37:46.339907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21fd64c94ab2'
down_revision = 'fd13519f15d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ctobdata', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ctobdata', 'status')
    # ### end Alembic commands ###
