"""empty message

Revision ID: 233b85cdb279
Revises: ee17db731714
Create Date: 2022-04-20 09:08:42.993276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233b85cdb279'
down_revision = 'ee17db731714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('receipt_num', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('receipt_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'receipt_num')
    op.drop_column('companies', 'receipt_num')
    # ### end Alembic commands ###
