"""empty message

Revision ID: 258982cd01b5
Revises: e9baea3c7798
Create Date: 2021-01-14 09:36:39.284293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258982cd01b5'
down_revision = 'e9baea3c7798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charges', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charges', 'state')
    # ### end Alembic commands ###
