"""empty message

Revision ID: 25a180566f66
Revises: badd70798693
Create Date: 2025-02-19 11:59:37.682720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a180566f66'
down_revision = 'badd70798693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paymentdetails', sa.Column('bankbiller', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paymentdetails', 'bankbiller')
    # ### end Alembic commands ###
