"""empty message

Revision ID: 268d40bd56fa
Revises: 2d442ab784d7
Create Date: 2021-06-09 10:18:24.988768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268d40bd56fa'
down_revision = '2d442ab784d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landlordsummaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('water', sa.Float(), nullable=True),
    sa.Column('rent', sa.Float(), nullable=True),
    sa.Column('garbage', sa.Float(), nullable=True),
    sa.Column('security', sa.Float(), nullable=True),
    sa.Column('electricity', sa.Float(), nullable=True),
    sa.Column('deposit', sa.Float(), nullable=True),
    sa.Column('arrears', sa.Float(), nullable=True),
    sa.Column('total_bill', sa.Float(), nullable=True),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('landlordsummaries')
    # ### end Alembic commands ###
