"""empty message

Revision ID: 29fdb36483b4
Revises: f38eb3e18656
Create Date: 2022-07-06 16:05:46.551281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29fdb36483b4'
down_revision = 'f38eb3e18656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permanenttenants', sa.Column('num_instalment', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permanenttenants', 'num_instalment')
    # ### end Alembic commands ###
