"""empty message

Revision ID: 2c6eecf58e70
Revises: af59afb130ec
Create Date: 2021-12-07 10:56:56.921451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6eecf58e70'
down_revision = 'af59afb130ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('logged_on', sa.DateTime(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logins')
    # ### end Alembic commands ###
