"""empty message

Revision ID: 2d442ab784d7
Revises: 90706c525998
Create Date: 2021-06-08 09:13:00.343198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d442ab784d7'
down_revision = '90706c525998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthlycharges', sa.Column('fine_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monthlycharges', 'fine_status')
    # ### end Alembic commands ###
