"""empty message

Revision ID: 2dbea9f0582e
Revises: 0ed25f57dc84
Create Date: 2022-06-23 13:10:53.623228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dbea9f0582e'
down_revision = '0ed25f57dc84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permanenttenants', sa.Column('deposit2', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permanenttenants', 'deposit2')
    # ### end Alembic commands ###
