"""empty message

Revision ID: 2e4f5ddc0801
Revises: ca161d08ecd3
Create Date: 2021-03-22 08:22:42.834897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e4f5ddc0801'
down_revision = 'ca161d08ecd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housecodes', sa.Column('watercharge', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('housecodes', 'watercharge')
    # ### end Alembic commands ###
