"""empty message

Revision ID: 31688597fe18
Revises: 29fdb36483b4
Create Date: 2022-07-06 18:24:05.404759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31688597fe18'
down_revision = '29fdb36483b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paymentschedules', sa.Column('payref', sa.VARCHAR(), nullable=True))
    op.add_column('paymentschedules', sa.Column('paytype', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paymentschedules', 'paytype')
    op.drop_column('paymentschedules', 'payref')
    # ### end Alembic commands ###
