"""empty message

Revision ID: 33c7edc19a93
Revises: 004e8c1c0b9b
Create Date: 2026-03-24 08:46:21.609637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33c7edc19a93'
down_revision = '004e8c1c0b9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthlycharges', sa.Column('payhold', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monthlycharges', 'payhold')
    # ### end Alembic commands ###
