"""empty message

Revision ID: 346a501f8b5a
Revises: 46af3d7a830e
Create Date: 2022-03-25 12:54:47.808730

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '346a501f8b5a'
down_revision = '46af3d7a830e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthlychargehistories')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthlychargehistories',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rent', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('water', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('garbage', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('security', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('electricity', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('maintenance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('agreement', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('deposit', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('penalty', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rent_balance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('water_balance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('garbage_balance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('security_balance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('electricity_balance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('maintenance_balance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('agreement_balance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('deposit_balance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('penalty_balance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rent_paid', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('water_paid', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('garbage_paid', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('security_paid', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('electricity_paid', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('maintenance_paid', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('agreement_paid', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('deposit_paid', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('penalty_paid', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('rent_due', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('water_due', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('garbage_due', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('security_due', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('electricity_due', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('maintenance_due', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('agreement_due', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('deposit_due', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('penalty_due', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('arrears', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_bill', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('paid_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('balance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pay_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fine_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fine_date', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sms_invoice', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email_invoice', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('smsid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('arrears_updated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('updated', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('apartment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('house_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('createdby', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('modifiedby', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('modifiedon', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], name='monthlychargehistories_apartment_id_fkey'),
    sa.ForeignKeyConstraint(['createdby'], ['users.id'], name='monthlychargehistories_createdby_fkey'),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], name='monthlychargehistories_house_id_fkey'),
    sa.ForeignKeyConstraint(['invoice_id'], ['monthlycharges.id'], name='monthlychargehistories_invoice_id_fkey'),
    sa.ForeignKeyConstraint(['modifiedby'], ['users.id'], name='monthlychargehistories_modifiedby_fkey'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='monthlychargehistories_tenant_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='monthlychargehistories_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='monthlychargehistories_pkey')
    )
    # ### end Alembic commands ###
