"""empty message

Revision ID: 34b26b9f6b14
Revises: 8dc151d97800
Create Date: 2022-05-15 13:48:55.902658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b26b9f6b14'
down_revision = '8dc151d97800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permanenttenants', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permanenttenants', 'status')
    # ### end Alembic commands ###
