"""empty message

Revision ID: 356deccc0db3
Revises: 7ac912245cb8
Create Date: 2021-02-08 19:15:48.382227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '356deccc0db3'
down_revision = '7ac912245cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meterreadings', sa.Column('reading_period', sa.DateTime(), nullable=True))
    op.drop_column('meterreadings', 'month')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meterreadings', sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('meterreadings', 'reading_period')
    # ### end Alembic commands ###
