"""empty message

Revision ID: 36dcadc90947
Revises: f34d7e100229
Create Date: 2021-04-07 15:28:44.461303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36dcadc90947'
down_revision = 'f34d7e100229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meterreadings', sa.Column('sms_invoice', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meterreadings', 'sms_invoice')
    # ### end Alembic commands ###
