"""empty message

Revision ID: 36dce0a4b1db
Revises: 2e4f5ddc0801
Create Date: 2021-03-30 06:08:02.130744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36dce0a4b1db'
down_revision = '2e4f5ddc0801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthlycharges', sa.Column('email_invoice', sa.String(), nullable=True))
    op.add_column('monthlycharges', sa.Column('sms_invoice', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monthlycharges', 'sms_invoice')
    op.drop_column('monthlycharges', 'email_invoice')
    # ### end Alembic commands ###
