"""empty message

Revision ID: 37a6b7b37965
Revises: 5479a8549fcc
Create Date: 2021-04-05 13:56:40.066864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37a6b7b37965'
down_revision = '5479a8549fcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housecodes', sa.Column('electricityrate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('housecodes', 'electricityrate')
    # ### end Alembic commands ###
