"""empty message

Revision ID: 394eca72576e
Revises: 
Create Date: 2023-01-18 06:18:41.307762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394eca72576e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('channel', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('discussion', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('subject', sa.String(), nullable=True))
    op.drop_column('conversations', 'action')
    op.drop_column('conversations', 'message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('conversations', sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('conversations', 'subject')
    op.drop_column('conversations', 'discussion')
    op.drop_column('conversations', 'channel')
    # ### end Alembic commands ###
