"""empty message

Revision ID: 39d0ca27cf7a
Revises: ecf7f7ff268c
Create Date: 2024-10-31 11:47:28.623754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d0ca27cf7a'
down_revision = 'ecf7f7ff268c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('modifiedon', sa.DateTime(), nullable=True),
    sa.Column('acceptedon', sa.DateTime(), nullable=True),
    sa.Column('posted_by', sa.Integer(), nullable=True),
    sa.Column('accepted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_requests')
    # ### end Alembic commands ###
