"""empty message

Revision ID: 39d641b060fc
Revises: 31688597fe18
Create Date: 2022-07-07 11:23:11.469572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d641b060fc'
down_revision = '31688597fe18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthlycharges', sa.Column('addfee', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('addfee_balance', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('addfee_due', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('addfee_paid', sa.Float(), nullable=True))
    op.add_column('payments', sa.Column('addfee_paid', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'addfee_paid')
    op.drop_column('monthlycharges', 'addfee_paid')
    op.drop_column('monthlycharges', 'addfee_due')
    op.drop_column('monthlycharges', 'addfee_balance')
    op.drop_column('monthlycharges', 'addfee')
    # ### end Alembic commands ###
