"""empty message

Revision ID: 39e254b4c08e
Revises: 101305ed5d84
Create Date: 2025-09-04 21:49:56.449818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '39e254b4c08e'
down_revision = '101305ed5d84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_transactions', sa.Column('quantity', sa.Float(), nullable=True))
    op.drop_column('stock_transactions', 'quantityy')
    op.add_column('stocksales', sa.Column('quantity', sa.Float(), nullable=True))
    op.drop_column('stocksales', 'quantityy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocksales', sa.Column('quantityy', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('stocksales', 'quantity')
    op.add_column('stock_transactions', sa.Column('quantityy', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('stock_transactions', 'quantity')
    # ### end Alembic commands ###
