"""empty message

Revision ID: 3adf11494f2f
Revises: 0aacc785b7a0
Create Date: 2022-07-04 18:23:09.103974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3adf11494f2f'
down_revision = '0aacc785b7a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('booking_paid', sa.Float(), nullable=True))
    op.add_column('payments', sa.Column('instalment_paid', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'instalment_paid')
    op.drop_column('payments', 'booking_paid')
    # ### end Alembic commands ###
