"""empty message

Revision ID: 3fcc63bd0d27
Revises: b0d20ac8af1e
Create Date: 2022-03-31 12:27:15.173936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fcc63bd0d27'
down_revision = 'b0d20ac8af1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permanenttenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uniquenameid', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('national_id', sa.String(), nullable=True),
    sa.Column('sms', sa.Boolean(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('accumulated_fine', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('initial_arrears', sa.Float(), nullable=True),
    sa.Column('multiple_houses', sa.Boolean(), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('housecodes', sa.Column('seweragerate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('housecodes', 'seweragerate')
    op.drop_table('permanenttenants')
    # ### end Alembic commands ###
