"""empty message

Revision ID: 40ec47ad79bb
Revises: 1006242dad87
Create Date: 2025-03-09 16:42:10.595930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40ec47ad79bb'
down_revision = '1006242dad87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenantdeposits', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenantdeposits', 'active')
    # ### end Alembic commands ###
