"""empty message

Revision ID: 4248341cdc35
Revises: 22e74eb041a0
Create Date: 2024-11-01 12:22:28.873871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4248341cdc35'
down_revision = '22e74eb041a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kceevents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('venue', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kceevents')
    # ### end Alembic commands ###
