"""empty message

Revision ID: 424e18a45c69
Revises: 4a293f793c3a
Create Date: 2024-11-21 13:21:10.587904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '424e18a45c69'
down_revision = '4a293f793c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('ref', sa.VARCHAR(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('reconciled', sa.Boolean(), nullable=True),
    sa.Column('transaction_type', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_transactions')
    # ### end Alembic commands ###
