"""empty message

Revision ID: 4268581af327
Revises: 40ec47ad79bb
Create Date: 2025-04-11 12:27:44.225663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4268581af327'
down_revision = '40ec47ad79bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_transactions', sa.Column('bank', sa.String(), nullable=True))
    op.add_column('app_transactions', sa.Column('house', sa.String(), nullable=True))
    op.add_column('app_transactions', sa.Column('pay_id', sa.Integer(), nullable=True))
    op.add_column('app_transactions', sa.Column('prop', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_transactions', 'prop')
    op.drop_column('app_transactions', 'pay_id')
    op.drop_column('app_transactions', 'house')
    op.drop_column('app_transactions', 'bank')
    # ### end Alembic commands ###
