"""empty message

Revision ID: 440132733d96
Revises: e31e73169b28
Create Date: 2021-03-03 03:17:00.025789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440132733d96'
down_revision = 'e31e73169b28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('original_amount', sa.Float(), nullable=True))
    op.add_column('payments', sa.Column('state', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('voided', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'voided')
    op.drop_column('payments', 'state')
    op.drop_column('payments', 'original_amount')
    # ### end Alembic commands ###
