"""empty message

Revision ID: 4516e8457810
Revises: 11cac1d24ceb
Create Date: 2021-07-07 01:18:48.483054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4516e8457810'
down_revision = '11cac1d24ceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'active')
    # ### end Alembic commands ###
