"""empty message

Revision ID: 464eecb7fe00
Revises: a641dc56d768
Create Date: 2023-05-26 10:10:18.922460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464eecb7fe00'
down_revision = 'a641dc56d768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentmessages', sa.Column('sms_period', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sentmessages', 'sms_period')
    # ### end Alembic commands ###
