"""empty message

Revision ID: 46d8ef309e2a
Revises: cec3aca2c41a
Create Date: 2021-01-29 10:11:03.499361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46d8ef309e2a'
down_revision = 'cec3aca2c41a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('dashboard_disp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'dashboard_disp')
    # ### end Alembic commands ###
