"""empty message

Revision ID: 48e54a2dec66
Revises: 9033d40fda21
Create Date: 2021-01-04 18:10:04.678376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48e54a2dec66'
down_revision = '9033d40fda21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meterreadings', sa.Column('date', sa.DateTime(), nullable=True))
    op.drop_column('meterreadings', 'date_read')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meterreadings', sa.Column('date_read', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('meterreadings', 'date')
    # ### end Alembic commands ###
