"""empty message

Revision ID: 49039ccb2e17
Revises: 
Create Date: 2023-04-26 14:46:35.468308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49039ccb2e17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('allsmssent', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('monthsmssent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'monthsmssent')
    op.drop_column('companies', 'allsmssent')
    # ### end Alembic commands ###
