"""empty message

Revision ID: 4a293f793c3a
Revises: a00b4f3191e5
Create Date: 2024-11-07 08:30:17.491903

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4a293f793c3a'
down_revision = 'a00b4f3191e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounttrails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('accounts', sa.Column('cash_balance', sa.Float(), nullable=True))
    op.add_column('accounts', sa.Column('float_balance', sa.Float(), nullable=True))
    op.drop_column('accounts', 'closing_balance')
    op.drop_column('accounts', 'opening_balance')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('opening_balance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('accounts', sa.Column('closing_balance', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('accounts', 'float_balance')
    op.drop_column('accounts', 'cash_balance')
    op.drop_table('accounttrails')
    # ### end Alembic commands ###
