"""empty message

Revision ID: 4a8953ebc348
Revises: 4c530a677850
Create Date: 2021-08-01 02:37:13.134038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a8953ebc348'
down_revision = '4c530a677850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('multiple_houses', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'multiple_houses')
    # ### end Alembic commands ###
