"""empty message

Revision ID: 4bfb71c8cad9
Revises: 2aa3c8421741
Create Date: 2022-06-30 11:20:11.154392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bfb71c8cad9'
down_revision = '2aa3c8421741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housecodes', sa.Column('billfrequency', sa.String(), nullable=True))
    op.add_column('housecodes', sa.Column('vatrate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('housecodes', 'vatrate')
    op.drop_column('housecodes', 'billfrequency')
    # ### end Alembic commands ###
