"""empty message

Revision ID: 4bfd7cf883e2
Revises: 05c651e2f014
Create Date: 2022-05-15 17:10:00.102735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bfd7cf883e2'
down_revision = '05c651e2f014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permanenttenants', sa.Column('classtype', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permanenttenants', 'classtype')
    # ### end Alembic commands ###
