"""empty message

Revision ID: 4c2480b419df
Revises: 89fcc9ccc747
Create Date: 2025-08-23 17:24:29.354913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c2480b419df'
down_revision = '89fcc9ccc747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stockitems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('selling_price', sa.Float(), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('contact_person', sa.VARCHAR(), nullable=True),
    sa.Column('contact_details', sa.VARCHAR(), nullable=True),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.Column('payment_terms', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('transaction_type', sa.VARCHAR(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price_per_unit', sa.Float(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['stockitems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocktakedbs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('stock_take_date', sa.DateTime(), nullable=True),
    sa.Column('expected_quantity', sa.Integer(), nullable=True),
    sa.Column('actual_quantity', sa.Integer(), nullable=True),
    sa.Column('discrepancy_notes', sa.VARCHAR(), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['stockitems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('damages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('damage_date', sa.DateTime(), nullable=True),
    sa.Column('damage_reason', sa.VARCHAR(), nullable=True),
    sa.Column('approval_status', sa.String(), nullable=True),
    sa.Column('approved_by', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.Column('stock_transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['stockitems.id'], ),
    sa.ForeignKeyConstraint(['stock_transaction_id'], ['stock_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('purchase_order_number', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.Column('stock_transaction_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stock_transaction_id'], ['stock_transactions.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stockexpenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('expense_date', sa.DateTime(), nullable=True),
    sa.Column('approval_status', sa.String(), nullable=True),
    sa.Column('approved_by', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.Column('stock_transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stock_transaction_id'], ['stock_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocksales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('sale_date', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.Column('stock_transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['stockitems.id'], ),
    sa.ForeignKeyConstraint(['stock_transaction_id'], ['stock_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stocksales')
    op.drop_table('stockexpenses')
    op.drop_table('purchases')
    op.drop_table('damages')
    op.drop_table('stocktakedbs')
    op.drop_table('stock_transactions')
    op.drop_table('suppliers')
    op.drop_table('stockitems')
    # ### end Alembic commands ###
