"""empty message

Revision ID: 4c530a677850
Revises: 6552e2036da0
Create Date: 2021-07-26 17:58:26.076204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c530a677850'
down_revision = '6552e2036da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthlycharges', sa.Column('arrears_updated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monthlycharges', 'arrears_updated')
    # ### end Alembic commands ###
