"""empty message

Revision ID: 4cbf61003b02
Revises: 62bc1e18af8b
Create Date: 2022-04-29 18:28:43.384749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cbf61003b02'
down_revision = '62bc1e18af8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paymentsdetails', sa.Column('bankpaybill', sa.VARCHAR(), nullable=True))
    op.add_column('paymentsdetails', sa.Column('mpesapaybill', sa.VARCHAR(), nullable=True))
    op.add_column('paymentsdetails', sa.Column('nartype', sa.VARCHAR(), nullable=True))
    op.add_column('paymentsdetails', sa.Column('paytype', sa.VARCHAR(), nullable=True))
    op.drop_column('paymentsdetails', 'shortcodeacc_type')
    op.drop_column('paymentsdetails', 'paymode')
    op.drop_column('paymentsdetails', 'shortcode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paymentsdetails', sa.Column('shortcode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('paymentsdetails', sa.Column('paymode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('paymentsdetails', sa.Column('shortcodeacc_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('paymentsdetails', 'paytype')
    op.drop_column('paymentsdetails', 'nartype')
    op.drop_column('paymentsdetails', 'mpesapaybill')
    op.drop_column('paymentsdetails', 'bankpaybill')
    # ### end Alembic commands ###
