"""empty message

Revision ID: 4f77df4046f4
Revises: e3680118b745
Create Date: 2021-09-08 16:05:49.366735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f77df4046f4'
down_revision = 'e3680118b745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthlycharges', sa.Column('fine_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monthlycharges', 'fine_date')
    # ### end Alembic commands ###
