"""empty message

Revision ID: 4ff3d54662f3
Revises: 97f020c779b5
Create Date: 2023-02-25 23:02:29.490280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ff3d54662f3'
down_revision = '97f020c779b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occupancy', sa.Column('invoiced', sa.Boolean(), nullable=True))
    op.drop_column('tenants', 'invoiced')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('invoiced', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('occupancy', 'invoiced')
    # ### end Alembic commands ###
