"""empty message

Revision ID: 51ef9bb049e9
Revises: 68e69256e05b
Create Date: 2021-08-02 20:45:27.086658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51ef9bb049e9'
down_revision = '68e69256e05b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('splitpayments', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'splitpayments', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'splitpayments', type_='foreignkey')
    op.drop_column('splitpayments', 'tenant_id')
    # ### end Alembic commands ###
