"""empty message

Revision ID: 528b3f8a5f5e
Revises: 
Create Date: 2023-04-27 12:55:12.537790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '528b3f8a5f5e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('smsbal', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'smsbal')
    # ### end Alembic commands ###
