"""empty message

Revision ID: 540367634fef
Revises: ee867eb15512
Create Date: 2025-01-04 19:22:24.765142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540367634fef'
down_revision = 'ee867eb15512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depositpayments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('deposit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deposit_id'], ['tenantdeposits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('depositpayments')
    # ### end Alembic commands ###
