"""empty message

Revision ID: 546fedaeefa7
Revises: 51ef9bb049e9
Create Date: 2021-08-27 04:44:37.177014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546fedaeefa7'
down_revision = '51ef9bb049e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('month_paid', sa.Integer(), nullable=True),
    sa.Column('receipt_number', sa.VARCHAR(), nullable=True),
    sa.Column('pay_date', sa.DateTime(), nullable=True),
    sa.Column('pay_period', sa.DateTime(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submissions')
    # ### end Alembic commands ###
