"""empty message

Revision ID: 5479a8549fcc
Revises: 0c8b147ad0c0
Create Date: 2021-04-01 11:54:05.527982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5479a8549fcc'
down_revision = '0c8b147ad0c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charges', sa.Column('elec_reading_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'charges', 'electricityreadings', ['elec_reading_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'charges', type_='foreignkey')
    op.drop_column('charges', 'elec_reading_id')
    # ### end Alembic commands ###
