"""empty message

Revision ID: 5937b5c2d37d
Revises: b7d16ba5293d
Create Date: 2021-01-22 13:23:21.708221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5937b5c2d37d'
down_revision = 'b7d16ba5293d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('meters_serial_number_key', 'meters', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('meters_serial_number_key', 'meters', ['serial_number'])
    # ### end Alembic commands ###
