"""empty message

Revision ID: 5a6d6bf0f797
Revises: 8d31f48f492f
Create Date: 2022-08-25 14:31:56.983047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a6d6bf0f797'
down_revision = '8d31f48f492f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenantdeposits', sa.Column('balance', sa.Float(), nullable=True))
    op.add_column('tenantdeposits', sa.Column('modifiedon', sa.DateTime(), nullable=True))
    op.add_column('tenantdeposits', sa.Column('otherdep', sa.Float(), nullable=True))
    op.add_column('tenantdeposits', sa.Column('paid', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenantdeposits', 'paid')
    op.drop_column('tenantdeposits', 'otherdep')
    op.drop_column('tenantdeposits', 'modifiedon')
    op.drop_column('tenantdeposits', 'balance')
    # ### end Alembic commands ###
