"""empty message

Revision ID: 5b0abac7087e
Revises: 440132733d96
Create Date: 2021-03-04 09:18:48.184887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0abac7087e'
down_revision = '440132733d96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('sms', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'sms')
    # ### end Alembic commands ###
