"""empty message

Revision ID: 5b3f6504d04f
Revises: ff1f2ccbf8fd
Create Date: 2025-08-31 16:42:00.243930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b3f6504d04f'
down_revision = 'ff1f2ccbf8fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_takes', sa.Column('stocktake_date', sa.DateTime(), nullable=True))
    op.add_column('stock_takes', sa.Column('stocktake_type', sa.VARCHAR(), nullable=True))
    op.drop_constraint('stock_takes_item_id_fkey', 'stock_takes', type_='foreignkey')
    op.drop_column('stock_takes', 'stock_take_date')
    op.drop_column('stock_takes', 'item_id')
    op.drop_column('stock_takes', 'stock_take_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_takes', sa.Column('stock_take_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stock_takes', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stock_takes', sa.Column('stock_take_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key('stock_takes_item_id_fkey', 'stock_takes', 'stockitems', ['item_id'], ['id'])
    op.drop_column('stock_takes', 'stocktake_type')
    op.drop_column('stock_takes', 'stocktake_date')
    # ### end Alembic commands ###
