"""empty message

Revision ID: 5b7d54ee31fd
Revises: d67f2176b61e
Create Date: 2024-06-07 23:56:19.773810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b7d54ee31fd'
down_revision = 'd67f2176b61e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('added_stock', sa.Integer(), nullable=True))
    op.add_column('stocks', sa.Column('selling_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'selling_price')
    op.drop_column('stocks', 'added_stock')
    # ### end Alembic commands ###
