"""empty message

Revision ID: 5ea0d8d3e308
Revises: 6c76ce0044ab
Create Date: 2021-06-04 16:55:43.881380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ea0d8d3e308'
down_revision = '6c76ce0044ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthlycharges', sa.Column('smsid', sa.VARCHAR(), nullable=True))
    op.add_column('payments', sa.Column('smsid', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'smsid')
    op.drop_column('monthlycharges', 'smsid')
    # ### end Alembic commands ###
