"""empty message

Revision ID: 60d8a83d1a3c
Revises: e2c82c25b459
Create Date: 2023-02-02 15:02:35.913356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d8a83d1a3c'
down_revision = 'e2c82c25b459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('address', sa.VARCHAR(), nullable=True))
    op.add_column('apartments', sa.Column('email', sa.VARCHAR(), nullable=True))
    op.add_column('apartments', sa.Column('phone', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'phone')
    op.drop_column('apartments', 'email')
    op.drop_column('apartments', 'address')
    # ### end Alembic commands ###
