"""empty message

Revision ID: 60dd37c838b1
Revises: f43318232ee3
Create Date: 2022-05-15 08:57:25.020796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60dd37c838b1'
down_revision = 'f43318232ee3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permanenttenants', sa.Column('rep_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'permanenttenants', 'salesreps', ['rep_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permanenttenants', type_='foreignkey')
    op.drop_column('permanenttenants', 'rep_id')
    # ### end Alembic commands ###
