"""empty message

Revision ID: 6255d5276afa
Revises: de1271e56130
Create Date: 2021-03-07 17:12:10.963650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6255d5276afa'
down_revision = 'de1271e56130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('pay_period', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'pay_period')
    # ### end Alembic commands ###
