"""empty message

Revision ID: 6283310dc369
Revises: 46d8ef309e2a
Create Date: 2021-02-02 00:02:45.739873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6283310dc369'
down_revision = '46d8ef309e2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('billing_period', sa.Integer(), nullable=True))
    op.drop_column('companies', 'dashboard_disp')
    op.add_column('meterreadings', sa.Column('month', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meterreadings', 'month')
    op.add_column('companies', sa.Column('dashboard_disp', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('companies', 'billing_period')
    # ### end Alembic commands ###
