"""empty message

Revision ID: 62bc1e18af8b
Revises: 233b85cdb279
Create Date: 2022-04-26 17:07:59.125415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62bc1e18af8b'
down_revision = '233b85cdb279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymentsdetails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paymode', sa.VARCHAR(), nullable=True),
    sa.Column('shortcode', sa.VARCHAR(), nullable=True),
    sa.Column('shortcodeacc_type', sa.VARCHAR(), nullable=True),
    sa.Column('bankname', sa.VARCHAR(), nullable=True),
    sa.Column('bankbranch', sa.VARCHAR(), nullable=True),
    sa.Column('bankaccountname', sa.VARCHAR(), nullable=True),
    sa.Column('bankaccountnumber', sa.VARCHAR(), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paymentsdetails')
    # ### end Alembic commands ###
