"""empty message

Revision ID: 63a02e220bf5
Revises: 88b6169e9fcb
Create Date: 2022-06-30 16:07:48.384369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63a02e220bf5'
down_revision = '88b6169e9fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landlordremittances', sa.Column('agent', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landlordremittances', 'agent')
    # ### end Alembic commands ###
