"""empty message

Revision ID: 6476e2281a9d
Revises: 88774749e8c2
Create Date: 2022-10-19 10:30:23.510970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6476e2281a9d'
down_revision = '88774749e8c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('feedback', sa.VARCHAR(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('leads', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('leads', 'lead_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('lead_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('leads', 'status')
    op.drop_table('conversations')
    # ### end Alembic commands ###
