"""empty message

Revision ID: 650905b51fcb
Revises: 6609ba14e64e
Create Date: 2022-01-24 19:02:40.562571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650905b51fcb'
down_revision = '6609ba14e64e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentmessages', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sentmessages', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sentmessages', type_='foreignkey')
    op.drop_column('sentmessages', 'company_id')
    # ### end Alembic commands ###
