"""empty message

Revision ID: 6516fd16ba45
Revises: 1feffcc9edbd
Create Date: 2025-07-27 16:13:40.284711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6516fd16ba45'
down_revision = '1feffcc9edbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('lock_status', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('updated_on', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('houses', 'updated_on')
    op.drop_column('houses', 'lock_status')
    # ### end Alembic commands ###
