"""empty message

Revision ID: 6552e2036da0
Revises: 4516e8457810
Create Date: 2021-07-14 20:17:12.089255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6552e2036da0'
down_revision = '4516e8457810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('rand_id', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'rand_id')
    # ### end Alembic commands ###
