"""empty message

Revision ID: 68e69256e05b
Revises: 4a8953ebc348
Create Date: 2021-08-02 20:22:09.281161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e69256e05b'
down_revision = '4a8953ebc348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('splitpayments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paymode', sa.String(), nullable=True),
    sa.Column('ref_number', sa.VARCHAR(), nullable=True),
    sa.Column('rand_id', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('payment_name', sa.String(), nullable=True),
    sa.Column('charged_amount', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('voided', sa.Boolean(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('original_amount', sa.Float(), nullable=True),
    sa.Column('pay_date', sa.DateTime(), nullable=True),
    sa.Column('pay_period', sa.DateTime(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('sms_status', sa.String(), nullable=True),
    sa.Column('email_status', sa.String(), nullable=True),
    sa.Column('smsid', sa.VARCHAR(), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('createdby', sa.Integer(), nullable=True),
    sa.Column('modifiedby', sa.Integer(), nullable=True),
    sa.Column('modifiedon', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ),
    sa.ForeignKeyConstraint(['createdby'], ['users.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.ForeignKeyConstraint(['modifiedby'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('splitpayments')
    # ### end Alembic commands ###
