"""empty message

Revision ID: 6b3701357315
Revises: 8fab976919bb
Create Date: 2022-05-05 09:53:42.936636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b3701357315'
down_revision = '8fab976919bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenantdeposits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rentdep', sa.Float(), nullable=True),
    sa.Column('waterdep', sa.Float(), nullable=True),
    sa.Column('elecdep', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenantdeposits')
    # ### end Alembic commands ###
