"""empty message

Revision ID: 6c76ce0044ab
Revises: fca85795b319
Create Date: 2021-06-04 12:52:59.524694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c76ce0044ab'
down_revision = 'fca85795b319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('payment_bank', sa.VARCHAR(), nullable=True))
    op.add_column('apartments', sa.Column('payment_bankacc', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'payment_bankacc')
    op.drop_column('apartments', 'payment_bank')
    # ### end Alembic commands ###
