"""empty message

Revision ID: 6d326ec09c8a
Revises: c2b1c20383cd
Create Date: 2022-10-26 18:59:20.205058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d326ec09c8a'
down_revision = 'c2b1c20383cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paymentschedules', sa.Column('rbalance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paymentschedules', 'rbalance')
    # ### end Alembic commands ###
