"""empty message

Revision ID: 723b842ce5cd
Revises: 2dbea9f0582e
Create Date: 2022-06-23 14:33:57.682958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '723b842ce5cd'
down_revision = '2dbea9f0582e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permanenttenants', sa.Column('checkin', sa.DateTime(), nullable=True))
    op.add_column('permanenttenants', sa.Column('resident_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permanenttenants', 'resident_type')
    op.drop_column('permanenttenants', 'checkin')
    # ### end Alembic commands ###
