"""empty message

Revision ID: 7a23bb65523b
Revises: e34f17e4eec2
Create Date: 2026-03-19 07:00:27.531799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a23bb65523b'
down_revision = 'e34f17e4eec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('proposed_data', sa.JSON(), nullable=True),
    sa.Column('original_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['monthlycharges.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['app_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('approvals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('approval_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modifiedon', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('initiated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name='approvals_approved_by_fkey'),
    sa.ForeignKeyConstraint(['company_id'], ['users.id'], name='approvals_company_id_fkey'),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], name='approvals_initiated_by_fkey'),
    sa.ForeignKeyConstraint(['invoice_id'], ['monthlycharges.id'], name='approvals_invoice_id_fkey'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name='approvals_payment_id_fkey'),
    sa.ForeignKeyConstraint(['transaction_id'], ['app_transactions.id'], name='approvals_transaction_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='approvals_pkey')
    )
    op.drop_table('change_requests')
    # ### end Alembic commands ###
