"""empty message

Revision ID: 7ac912245cb8
Revises: d91c7b5d322d
Create Date: 2021-02-08 14:10:00.730414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac912245cb8'
down_revision = 'd91c7b5d322d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('garbage_collector_tel', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'garbage_collector_tel')
    # ### end Alembic commands ###
