"""empty message

Revision ID: 7b9ba58efbcf
Revises: 4268581af327
Create Date: 2025-04-11 15:06:26.553420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b9ba58efbcf'
down_revision = '4268581af327'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_transactions', sa.Column('paid_ll', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_transactions', 'paid_ll')
    # ### end Alembic commands ###
