"""empty message

Revision ID: 7d990fd68977
Revises: 4bfb71c8cad9
Create Date: 2022-06-30 14:44:52.471950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7d990fd68977'
down_revision = '4bfb71c8cad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landlordremittances', sa.Column('expenses', sa.Float(), nullable=True))
    op.add_column('landlordremittances', sa.Column('llbbf', sa.Float(), nullable=True))
    op.add_column('landlordremittances', sa.Column('llbcf', sa.Float(), nullable=True))
    op.add_column('landlordremittances', sa.Column('payable', sa.Float(), nullable=True))
    op.add_column('landlordremittances', sa.Column('tntbbf', sa.Float(), nullable=True))
    op.add_column('landlordremittances', sa.Column('tntbcf', sa.Float(), nullable=True))
    op.drop_column('landlordremittances', 'll_balbf')
    op.drop_column('landlordremittances', 'll_balcf')
    op.drop_column('landlordremittances', 't_balbf')
    op.drop_column('landlordremittances', 't_balcf')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landlordremittances', sa.Column('t_balcf', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('landlordremittances', sa.Column('t_balbf', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('landlordremittances', sa.Column('ll_balcf', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('landlordremittances', sa.Column('ll_balbf', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('landlordremittances', 'tntbcf')
    op.drop_column('landlordremittances', 'tntbbf')
    op.drop_column('landlordremittances', 'payable')
    op.drop_column('landlordremittances', 'llbcf')
    op.drop_column('landlordremittances', 'llbbf')
    op.drop_column('landlordremittances', 'expenses')
    # ### end Alembic commands ###
