"""empty message

Revision ID: 7f3773c72f36
Revises: dcc33a0e5ddb
Create Date: 2022-04-12 15:03:37.770774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f3773c72f36'
down_revision = 'dcc33a0e5ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('servicetarget', sa.String(), nullable=True))
    op.add_column('houses', sa.Column('watertarget', sa.String(), nullable=True))
    op.add_column('permanenttenants', sa.Column('tenant_type', sa.String(), nullable=True))
    op.add_column('tenants', sa.Column('tenant_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'tenant_type')
    op.drop_column('permanenttenants', 'tenant_type')
    op.drop_column('houses', 'watertarget')
    op.drop_column('houses', 'servicetarget')
    # ### end Alembic commands ###
