"""empty message

Revision ID: 813cd10cabfc
Revises: b456f040aec8
Create Date: 2022-05-31 11:05:40.264764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '813cd10cabfc'
down_revision = 'b456f040aec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banksdata', sa.Column('dataType', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banksdata', 'dataType')
    # ### end Alembic commands ###
