"""empty message

Revision ID: 8277538fadcb
Revises: 7d990fd68977
Create Date: 2022-06-30 15:27:46.450379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8277538fadcb'
down_revision = '7d990fd68977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landlordremittances', sa.Column('prop', sa.VARCHAR(), nullable=True))
    op.add_column('landlordremittances', sa.Column('propcode', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landlordremittances', 'propcode')
    op.drop_column('landlordremittances', 'prop')
    # ### end Alembic commands ###
