"""empty message

Revision ID: 83e1aef2e8c8
Revises: 0f96cfde67b9
Create Date: 2022-07-14 20:23:07.291390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83e1aef2e8c8'
down_revision = '0f96cfde67b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bank', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('bankacc', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bankacc')
    op.drop_column('users', 'bank')
    # ### end Alembic commands ###
