"""empty message

Revision ID: 849f9e84cbe6
Revises: 1c5523b849a9
Create Date: 2021-03-11 07:46:53.952727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849f9e84cbe6'
down_revision = '1c5523b849a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internalexpenses', sa.Column('cost', sa.Float(), nullable=True))
    op.add_column('internalexpenses', sa.Column('deposit', sa.Float(), nullable=True))
    op.add_column('internalexpenses', sa.Column('house', sa.VARCHAR(), nullable=True))
    op.add_column('internalexpenses', sa.Column('labour', sa.Float(), nullable=True))
    op.add_column('internalexpenses', sa.Column('qty', sa.VARCHAR(), nullable=True))
    op.drop_column('internalexpenses', 'invoice')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internalexpenses', sa.Column('invoice', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('internalexpenses', 'qty')
    op.drop_column('internalexpenses', 'labour')
    op.drop_column('internalexpenses', 'house')
    op.drop_column('internalexpenses', 'deposit')
    op.drop_column('internalexpenses', 'cost')
    # ### end Alembic commands ###
