"""empty message

Revision ID: 88774749e8c2
Revises: 1051b9804de9
Create Date: 2022-10-17 12:45:54.116283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88774749e8c2'
down_revision = '1051b9804de9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'leads', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_column('leads', 'company_id')
    # ### end Alembic commands ###
