"""empty message

Revision ID: 88b6169e9fcb
Revises: 8277538fadcb
Create Date: 2022-06-30 16:07:37.494318

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88b6169e9fcb'
down_revision = '8277538fadcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landlordremittances', 'agent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landlordremittances', sa.Column('agent', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
