"""empty message

Revision ID: 89fcc9ccc747
Revises: 6516fd16ba45
Create Date: 2025-07-27 16:21:39.637626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89fcc9ccc747'
down_revision = '6516fd16ba45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('locked', sa.Boolean(), nullable=True))
    op.drop_column('houses', 'lock_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('lock_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('houses', 'locked')
    # ### end Alembic commands ###
