"""empty message

Revision ID: 8a401e4cec0e
Revises: 650905b51fcb
Create Date: 2022-01-25 10:30:07.029146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a401e4cec0e'
down_revision = '650905b51fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('commission_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'commission_type')
    # ### end Alembic commands ###
