"""empty message

Revision ID: 8bfc584dbd5f
Revises: 8c9405854b11
Create Date: 2022-08-11 15:54:45.932780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bfc584dbd5f'
down_revision = '8c9405854b11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housecodes', sa.Column('depnum', sa.Integer(), nullable=True))
    op.drop_column('housecodes', 'numdep')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housecodes', sa.Column('numdep', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('housecodes', 'depnum')
    # ### end Alembic commands ###
