"""empty message

Revision ID: 8c720801883c
Revises: e61461f83bf9
Create Date: 2020-11-17 07:24:38.060843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c720801883c'
down_revision = 'e61461f83bf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('initial_arrears', sa.Float(), nullable=True))
    op.drop_column('tenants', 'arrears')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('arrears', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('tenants', 'initial_arrears')
    # ### end Alembic commands ###
