"""empty message

Revision ID: 8c9405854b11
Revises: a0dea36c7872
Create Date: 2022-08-11 15:23:11.585012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c9405854b11'
down_revision = 'a0dea36c7872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housecodes', sa.Column('discount', sa.Float(), nullable=True))
    op.add_column('housecodes', sa.Column('numdep', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('housecodes', 'numdep')
    op.drop_column('housecodes', 'discount')
    # ### end Alembic commands ###
