"""empty message

Revision ID: 8d31f48f492f
Revises: 8bfc584dbd5f
Create Date: 2022-08-12 11:59:02.790447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d31f48f492f'
down_revision = '8bfc584dbd5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenantdeposits', sa.Column('ptenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tenantdeposits', 'permanenttenants', ['ptenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenantdeposits', type_='foreignkey')
    op.drop_column('tenantdeposits', 'ptenant_id')
    # ### end Alembic commands ###
