"""empty message

Revision ID: 8dc151d97800
Revises: e4c01de6aade
Create Date: 2022-05-15 10:40:28.969490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dc151d97800'
down_revision = 'e4c01de6aade'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('houses', 'status')
    # ### end Alembic commands ###
