"""empty message

Revision ID: 8fab976919bb
Revises: 4cbf61003b02
Create Date: 2022-04-29 21:43:59.619860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fab976919bb'
down_revision = '4cbf61003b02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymentdetails',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paytype', sa.VARCHAR(), nullable=True),
    sa.Column('nartype', sa.VARCHAR(), nullable=True),
    sa.Column('mpesapaybill', sa.VARCHAR(), nullable=True),
    sa.Column('bankname', sa.VARCHAR(), nullable=True),
    sa.Column('bankbranch', sa.VARCHAR(), nullable=True),
    sa.Column('bankaccountname', sa.VARCHAR(), nullable=True),
    sa.Column('bankaccountnumber', sa.VARCHAR(), nullable=True),
    sa.Column('bankpaybill', sa.VARCHAR(), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('paymentsdetails')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymentsdetails',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('bankname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bankbranch', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bankaccountname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bankaccountnumber', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('apartment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bankpaybill', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mpesapaybill', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nartype', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('paytype', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], name='paymentsdetails_apartment_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='paymentsdetails_pkey')
    )
    op.drop_table('paymentdetails')
    # ### end Alembic commands ###
