"""empty message

Revision ID: 9167fd25cf57
Revises: ad84e615a5f3
Create Date: 2023-11-22 14:54:03.128552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9167fd25cf57'
down_revision = 'ad84e615a5f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthlychargehistories', sa.Column('dep_journal', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monthlychargehistories', 'dep_journal')
    # ### end Alembic commands ###
