"""empty message

Revision ID: 91a015969381
Revises: 48e54a2dec66
Create Date: 2021-01-10 00:34:32.156780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91a015969381'
down_revision = '48e54a2dec66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('quotamonth', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('remainingsms', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('smsquota', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'smsquota')
    op.drop_column('companies', 'remainingsms')
    op.drop_column('companies', 'quotamonth')
    # ### end Alembic commands ###
