"""empty message

Revision ID: 925e1609c2ff
Revises: 356deccc0db3
Create Date: 2021-02-08 19:20:45.541296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '925e1609c2ff'
down_revision = '356deccc0db3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'billing_period')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('billing_period', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
