"""empty message

Revision ID: 93e032a768ab
Revises: a43538fcb13a
Create Date: 2021-12-14 00:04:22.265576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e032a768ab'
down_revision = 'a43538fcb13a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logins', sa.Column('invoice_frequency', sa.Integer(), nullable=True))
    op.add_column('logins', sa.Column('payment_frequency', sa.Integer(), nullable=True))
    op.add_column('logins', sa.Column('report_frequency', sa.Integer(), nullable=True))
    op.add_column('logins', sa.Column('search_frequency', sa.Integer(), nullable=True))
    op.add_column('logins', sa.Column('tenant_frequency', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logins', 'tenant_frequency')
    op.drop_column('logins', 'search_frequency')
    op.drop_column('logins', 'report_frequency')
    op.drop_column('logins', 'payment_frequency')
    op.drop_column('logins', 'invoice_frequency')
    # ### end Alembic commands ###
