"""empty message

Revision ID: 9720824e393e
Revises: 1dc3d3dcfc3a
Create Date: 2024-09-11 18:17:11.412156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9720824e393e'
down_revision = '1dc3d3dcfc3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('floor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('houses', 'floor')
    # ### end Alembic commands ###
