"""empty message

Revision ID: 97f020c779b5
Revises: d16af2ec6e7e
Create Date: 2023-02-25 22:54:47.943353

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '97f020c779b5'
down_revision = 'd16af2ec6e7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occupancy', sa.Column('agreed_rates', sa.Float(), nullable=True))
    op.drop_column('tenants', 'agreed_rates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('agreed_rates', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('occupancy', 'agreed_rates')
    # ### end Alembic commands ###
