"""empty message

Revision ID: 987ea5a3ce93
Revises: 25a180566f66
Create Date: 2025-02-20 16:43:29.823392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987ea5a3ce93'
down_revision = '25a180566f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_transactions', sa.Column('trans_desc', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_transactions', 'trans_desc')
    # ### end Alembic commands ###
