"""empty message

Revision ID: 9a08d0b49fa2
Revises: f7d3c06d9323
Create Date: 2022-06-20 12:20:31.357847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a08d0b49fa2'
down_revision = 'f7d3c06d9323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landlordremittances', sa.Column('commission', sa.Float(), nullable=True))
    op.add_column('landlordremittances', sa.Column('status', sa.String(), nullable=True))
    op.add_column('landlordremittances', sa.Column('t_balcf', sa.Float(), nullable=True))
    op.add_column('landlordremittances', sa.Column('utilities_paid', sa.Float(), nullable=True))
    op.drop_column('landlordremittances', 'commision')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landlordremittances', sa.Column('commision', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('landlordremittances', 'utilities_paid')
    op.drop_column('landlordremittances', 't_balcf')
    op.drop_column('landlordremittances', 'status')
    op.drop_column('landlordremittances', 'commission')
    # ### end Alembic commands ###
