"""empty message

Revision ID: 9c805c093179
Revises: c89458e24736
Create Date: 2023-02-23 04:51:22.108892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c805c093179'
down_revision = 'c89458e24736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occupancy', sa.Column('checkout_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('occupancy', 'checkout_date')
    # ### end Alembic commands ###
