"""empty message

Revision ID: 9d076142005b
Revises: c21c61415386
Create Date: 2022-09-22 15:22:51.280529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d076142005b'
down_revision = 'c21c61415386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housecodes', sa.Column('int_commission', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('housecodes', 'int_commission')
    # ### end Alembic commands ###
