"""empty message

Revision ID: a00b4f3191e5
Revises: 4248341cdc35
Create Date: 2024-11-06 11:23:35.119972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a00b4f3191e5'
down_revision = '4248341cdc35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('modifiedon', sa.DateTime(), nullable=True),
    sa.Column('acceptedon', sa.DateTime(), nullable=True),
    sa.Column('posted_by', sa.Integer(), nullable=True),
    sa.Column('accepted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
