"""empty message

Revision ID: a0dea36c7872
Revises: 83e1aef2e8c8
Create Date: 2022-07-20 15:58:26.062162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0dea36c7872'
down_revision = '83e1aef2e8c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housecodes', sa.Column('carddep', sa.Float(), nullable=True))
    op.add_column('housecodes', sa.Column('otherdep', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('housecodes', 'otherdep')
    op.drop_column('housecodes', 'carddep')
    # ### end Alembic commands ###
