"""empty message

Revision ID: a43538fcb13a
Revises: bb0044d41e40
Create Date: 2021-12-09 11:01:49.078259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a43538fcb13a'
down_revision = 'bb0044d41e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthlycharges', sa.Column('agreement_due', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('deposit_due', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('electricity_due', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('garbage_due', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('maintenance_due', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('penalty_due', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('rent_due', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('security_due', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('water_due', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monthlycharges', 'water_due')
    op.drop_column('monthlycharges', 'security_due')
    op.drop_column('monthlycharges', 'rent_due')
    op.drop_column('monthlycharges', 'penalty_due')
    op.drop_column('monthlycharges', 'maintenance_due')
    op.drop_column('monthlycharges', 'garbage_due')
    op.drop_column('monthlycharges', 'electricity_due')
    op.drop_column('monthlycharges', 'deposit_due')
    op.drop_column('monthlycharges', 'agreement_due')
    # ### end Alembic commands ###
