"""empty message

Revision ID: a475d964a1a4
Revises: 93e032a768ab
Create Date: 2021-12-20 12:35:23.361495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a475d964a1a4'
down_revision = '93e032a768ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reminders', 'apartments', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reminders', type_='foreignkey')
    op.drop_column('reminders', 'company_id')
    # ### end Alembic commands ###
