"""empty message

Revision ID: a50c2f7c1f79
Revises: c173b45099fb
Create Date: 2024-12-18 11:04:52.100825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50c2f7c1f79'
down_revision = 'c173b45099fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounttrails', sa.Column('status', sa.String(), nullable=True))
    op.add_column('accounttrails', sa.Column('ttype', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounttrails', 'ttype')
    op.drop_column('accounttrails', 'status')
    # ### end Alembic commands ###
