"""empty message

Revision ID: a51f02d61729
Revises: 63a02e220bf5
Create Date: 2022-07-01 12:14:52.952613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a51f02d61729'
down_revision = '63a02e220bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('housecodes', 'billfrequency')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housecodes', sa.Column('billfrequency', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
