"""empty message

Revision ID: a989bcf59f0c
Revises: 
Create Date: 2023-02-23 19:24:06.567204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a989bcf59f0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occupancy', sa.Column('checkin_date', sa.DateTime(), nullable=True))
    op.add_column('occupancy', sa.Column('checkout_date', sa.DateTime(), nullable=True))
    op.add_column('occupancy', sa.Column('days_extended', sa.Integer(), nullable=True))
    op.add_column('permanenttenants', sa.Column('randid', sa.VARCHAR(), nullable=True))
    op.add_column('tenants', sa.Column('accepted_terms', sa.Boolean(), nullable=True))
    op.add_column('tenants', sa.Column('agreed_rates', sa.Float(), nullable=True))
    op.add_column('tenants', sa.Column('invoiced', sa.Boolean(), nullable=True))
    op.add_column('tenants', sa.Column('randid', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'randid')
    op.drop_column('tenants', 'invoiced')
    op.drop_column('tenants', 'agreed_rates')
    op.drop_column('tenants', 'accepted_terms')
    op.drop_column('permanenttenants', 'randid')
    op.drop_column('occupancy', 'days_extended')
    op.drop_column('occupancy', 'checkout_date')
    op.drop_column('occupancy', 'checkin_date')
    # ### end Alembic commands ###
