"""empty message

Revision ID: ad84e615a5f3
Revises: 20b78ce69b69
Create Date: 2023-11-07 17:04:43.354534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad84e615a5f3'
down_revision = '20b78ce69b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('vacate_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'vacate_date')
    # ### end Alembic commands ###
