"""empty message

Revision ID: af4f1ac46686
Revises: 3fcc63bd0d27
Create Date: 2022-03-31 12:33:14.874868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af4f1ac46686'
down_revision = '3fcc63bd0d27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('internalmessages', sa.Column('ptenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'internalmessages', 'permanenttenants', ['ptenant_id'], ['id'])
    op.add_column('mpesadata', sa.Column('ptenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mpesadata', 'permanenttenants', ['ptenant_id'], ['id'])
    op.add_column('mpesarequestdata', sa.Column('ptenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'mpesarequestdata', 'permanenttenants', ['ptenant_id'], ['id'])
    op.add_column('payments', sa.Column('ptenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payments', 'permanenttenants', ['ptenant_id'], ['id'])
    op.add_column('sentmessages', sa.Column('ptenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sentmessages', 'permanenttenants', ['ptenant_id'], ['id'])
    op.add_column('tenantrequests', sa.Column('ptenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tenantrequests', 'permanenttenants', ['ptenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenantrequests', type_='foreignkey')
    op.drop_column('tenantrequests', 'ptenant_id')
    op.drop_constraint(None, 'sentmessages', type_='foreignkey')
    op.drop_column('sentmessages', 'ptenant_id')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'ptenant_id')
    op.drop_constraint(None, 'mpesarequestdata', type_='foreignkey')
    op.drop_column('mpesarequestdata', 'ptenant_id')
    op.drop_constraint(None, 'mpesadata', type_='foreignkey')
    op.drop_column('mpesadata', 'ptenant_id')
    op.drop_constraint(None, 'internalmessages', type_='foreignkey')
    op.drop_column('internalmessages', 'ptenant_id')
    # ### end Alembic commands ###
