"""empty message

Revision ID: af59afb130ec
Revises: 155573d2c301
Create Date: 2021-12-01 04:36:16.193971

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af59afb130ec'
down_revision = '155573d2c301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientbills', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('clientbills', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientbills', sa.Column('text', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('clientbills', 'description')
    # ### end Alembic commands ###
