"""empty message

Revision ID: afc9ea0c797e
Revises: f67b62fa2b23
Create Date: 2022-10-11 13:21:34.950303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc9ea0c797e'
down_revision = 'f67b62fa2b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housecodes', sa.Column('deposit', sa.Float(), nullable=True))
    op.add_column('housecodes', sa.Column('instalments', sa.Integer(), nullable=True))
    op.add_column('housecodes', sa.Column('percentage_deposit', sa.Float(), nullable=True))
    op.add_column('housecodes', sa.Column('percentage_discount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('housecodes', 'percentage_discount')
    op.drop_column('housecodes', 'percentage_deposit')
    op.drop_column('housecodes', 'instalments')
    op.drop_column('housecodes', 'deposit')
    # ### end Alembic commands ###
