"""empty message

Revision ID: b006132ca32a
Revises: be6e06b61253
Create Date: 2022-03-25 11:17:32.545027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b006132ca32a'
down_revision = 'be6e06b61253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthlychargehistories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('rent', sa.Float(), nullable=True),
    sa.Column('water', sa.Float(), nullable=True),
    sa.Column('garbage', sa.Float(), nullable=True),
    sa.Column('security', sa.Float(), nullable=True),
    sa.Column('electricity', sa.Float(), nullable=True),
    sa.Column('maintenance', sa.Float(), nullable=True),
    sa.Column('agreement', sa.Float(), nullable=True),
    sa.Column('deposit', sa.Float(), nullable=True),
    sa.Column('penalty', sa.Float(), nullable=True),
    sa.Column('rent_balance', sa.Float(), nullable=True),
    sa.Column('water_balance', sa.Float(), nullable=True),
    sa.Column('garbage_balance', sa.Float(), nullable=True),
    sa.Column('security_balance', sa.Float(), nullable=True),
    sa.Column('electricity_balance', sa.Float(), nullable=True),
    sa.Column('maintenance_balance', sa.Float(), nullable=True),
    sa.Column('agreement_balance', sa.Float(), nullable=True),
    sa.Column('deposit_balance', sa.Float(), nullable=True),
    sa.Column('penalty_balance', sa.Float(), nullable=True),
    sa.Column('rent_paid', sa.Float(), nullable=True),
    sa.Column('water_paid', sa.Float(), nullable=True),
    sa.Column('garbage_paid', sa.Float(), nullable=True),
    sa.Column('security_paid', sa.Float(), nullable=True),
    sa.Column('electricity_paid', sa.Float(), nullable=True),
    sa.Column('maintenance_paid', sa.Float(), nullable=True),
    sa.Column('agreement_paid', sa.Float(), nullable=True),
    sa.Column('deposit_paid', sa.Float(), nullable=True),
    sa.Column('penalty_paid', sa.Float(), nullable=True),
    sa.Column('rent_due', sa.Float(), nullable=True),
    sa.Column('water_due', sa.Float(), nullable=True),
    sa.Column('garbage_due', sa.Float(), nullable=True),
    sa.Column('security_due', sa.Float(), nullable=True),
    sa.Column('electricity_due', sa.Float(), nullable=True),
    sa.Column('maintenance_due', sa.Float(), nullable=True),
    sa.Column('agreement_due', sa.Float(), nullable=True),
    sa.Column('deposit_due', sa.Float(), nullable=True),
    sa.Column('penalty_due', sa.Float(), nullable=True),
    sa.Column('arrears', sa.Float(), nullable=True),
    sa.Column('total_bill', sa.Float(), nullable=True),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('pay_date', sa.DateTime(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('fine_status', sa.String(), nullable=True),
    sa.Column('fine_date', sa.Integer(), nullable=True),
    sa.Column('sms_invoice', sa.String(), nullable=True),
    sa.Column('email_invoice', sa.String(), nullable=True),
    sa.Column('smsid', sa.VARCHAR(), nullable=True),
    sa.Column('arrears_updated', sa.Boolean(), nullable=True),
    sa.Column('updated', sa.Boolean(), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('createdby', sa.Integer(), nullable=True),
    sa.Column('modifiedby', sa.Integer(), nullable=True),
    sa.Column('modifiedon', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ),
    sa.ForeignKeyConstraint(['createdby'], ['users.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['monthlycharges.id'], ),
    sa.ForeignKeyConstraint(['modifiedby'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthlychargehistories')
    # ### end Alembic commands ###
