"""empty message

Revision ID: b412fe74a31d
Revises: dbf718ce47c2
Create Date: 2023-03-01 10:58:29.585246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b412fe74a31d'
down_revision = 'dbf718ce47c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('address', sa.VARCHAR(), nullable=True))
    op.add_column('apartments', sa.Column('email', sa.VARCHAR(), nullable=True))
    op.add_column('apartments', sa.Column('phone', sa.VARCHAR(), nullable=True))
    op.add_column('users', sa.Column('softdelete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'softdelete')
    op.drop_column('apartments', 'phone')
    op.drop_column('apartments', 'email')
    op.drop_column('apartments', 'address')
    # ### end Alembic commands ###
