"""empty message

Revision ID: b456f040aec8
Revises: 4bfd7cf883e2
Create Date: 2022-05-31 10:58:54.195145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b456f040aec8'
down_revision = '4bfd7cf883e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banksdata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.Column('billNumber', sa.VARCHAR(), nullable=True),
    sa.Column('billAmount', sa.Float(), nullable=True),
    sa.Column('customerRefNumber', sa.VARCHAR(), nullable=True),
    sa.Column('bankReference', sa.VARCHAR(), nullable=True),
    sa.Column('transParticular', sa.VARCHAR(), nullable=True),
    sa.Column('paymentMode', sa.VARCHAR(), nullable=True),
    sa.Column('post_date', sa.DateTime(), nullable=True),
    sa.Column('transDate', sa.VARCHAR(), nullable=True),
    sa.Column('phoneNumber', sa.VARCHAR(), nullable=True),
    sa.Column('debitAccount', sa.VARCHAR(), nullable=True),
    sa.Column('debitCustName', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banksdata')
    # ### end Alembic commands ###
