"""empty message

Revision ID: b633a47db697
Revises: 
Create Date: 2023-03-02 17:02:07.891322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b633a47db697'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occupancy', sa.Column('days', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('occupancy', 'days')
    # ### end Alembic commands ###
