"""empty message

Revision ID: b79b643d46a9
Revises: e29b259c7447
Create Date: 2024-12-19 14:24:13.842251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b79b643d46a9'
down_revision = 'e29b259c7447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounttrails', sa.Column('modifiedon', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounttrails', 'modifiedon')
    # ### end Alembic commands ###
