"""empty message

Revision ID: b7d16ba5293d
Revises: 5cea381ee08b
Create Date: 2021-01-18 20:29:02.087524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7d16ba5293d'
down_revision = '5cea381ee08b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toggledata')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toggledata',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='toggledata_pkey')
    )
    # ### end Alembic commands ###
