"""empty message

Revision ID: b814ae8de5f2
Revises: 2edba723061f
Create Date: 2021-07-03 18:17:24.713463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b814ae8de5f2'
down_revision = '2edba723061f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthlycharges', sa.Column('createdby', sa.Integer(), nullable=True))
    op.add_column('monthlycharges', sa.Column('modifiedby', sa.Integer(), nullable=True))
    op.add_column('monthlycharges', sa.Column('modifiedon', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'monthlycharges', 'users', ['createdby'], ['id'])
    op.create_foreign_key(None, 'monthlycharges', 'users', ['modifiedby'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'monthlycharges', type_='foreignkey')
    op.drop_constraint(None, 'monthlycharges', type_='foreignkey')
    op.drop_column('monthlycharges', 'modifiedon')
    op.drop_column('monthlycharges', 'modifiedby')
    op.drop_column('monthlycharges', 'createdby')
    # ### end Alembic commands ###
