"""empty message

Revision ID: badd70798693
Revises: 540367634fef
Create Date: 2025-02-18 17:18:52.308619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'badd70798693'
down_revision = '540367634fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paymentdetails', sa.Column('prefix', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paymentdetails', 'prefix')
    # ### end Alembic commands ###
