"""empty message

Revision ID: bb0044d41e40
Revises: 2c6eecf58e70
Create Date: 2021-12-07 12:49:32.178337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb0044d41e40'
down_revision = '2c6eecf58e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logins', sa.Column('logged_on_last', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logins', 'logged_on_last')
    # ### end Alembic commands ###
