"""empty message

Revision ID: bbbeaae3229b
Revises: 5b0abac7087e
Create Date: 2021-03-04 13:15:25.827514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbbeaae3229b'
down_revision = '5b0abac7087e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('commssion', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'commssion')
    # ### end Alembic commands ###
