"""empty message

Revision ID: bce9496884da
Revises: f04a062bc927
Create Date: 2026-02-23 12:38:25.654403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce9496884da'
down_revision = 'f04a062bc927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_transactions', sa.Column('garbage', sa.Float(), nullable=True))
    op.add_column('app_transactions', sa.Column('rent', sa.Float(), nullable=True))
    op.add_column('app_transactions', sa.Column('water', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_transactions', 'water')
    op.drop_column('app_transactions', 'rent')
    op.drop_column('app_transactions', 'garbage')
    # ### end Alembic commands ###
