"""empty message

Revision ID: be6e06b61253
Revises: ee458a665154
Create Date: 2022-03-23 06:20:19.742542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be6e06b61253'
down_revision = 'ee458a665154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('activation_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'activation_link')
    # ### end Alembic commands ###
