"""empty message

Revision ID: c21c61415386
Revises: 0921dd5bc976
Create Date: 2022-09-09 19:44:56.271028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c21c61415386'
down_revision = '0921dd5bc976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ctobdata', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('ctobdata', sa.Column('data_type', sa.String(), nullable=True))
    op.add_column('ctobdata', sa.Column('mode', sa.String(), nullable=True))
    op.create_foreign_key(None, 'ctobdata', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ctobdata', type_='foreignkey')
    op.drop_column('ctobdata', 'mode')
    op.drop_column('ctobdata', 'data_type')
    op.drop_column('ctobdata', 'company_id')
    # ### end Alembic commands ###
