"""empty message

Revision ID: c2b1c20383cd
Revises: 6476e2281a9d
Create Date: 2022-10-19 12:58:46.180806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b1c20383cd'
down_revision = '6476e2281a9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permanenttenants', sa.Column('wallet', sa.Float(), nullable=True))
    op.add_column('tenants', sa.Column('wallet', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'wallet')
    op.drop_column('permanenttenants', 'wallet')
    # ### end Alembic commands ###
