"""empty message

Revision ID: c32df49d89fb
Revises: a51f02d61729
Create Date: 2022-07-01 12:15:07.368735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c32df49d89fb'
down_revision = 'a51f02d61729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housecodes', sa.Column('billfrequency', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('housecodes', 'billfrequency')
    # ### end Alembic commands ###
