"""empty message

Revision ID: c389592a9fa7
Revises: f6a181b3a9e1
Create Date: 2023-02-23 05:03:47.036532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c389592a9fa7'
down_revision = 'f6a181b3a9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('accepted_terms', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'accepted_terms')
    # ### end Alembic commands ###
