"""empty message

Revision ID: c53949792c64
Revises: fcf44e4d5722
Create Date: 2021-07-06 09:06:23.796262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c53949792c64'
down_revision = 'fcf44e4d5722'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('payment_bank', sa.VARCHAR(), nullable=True))
    op.add_column('houses', sa.Column('payment_bankacc', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('houses', 'payment_bankacc')
    op.drop_column('houses', 'payment_bank')
    # ### end Alembic commands ###
