"""empty message

Revision ID: c69596a69add
Revises: 60dd37c838b1
Create Date: 2022-05-15 08:59:04.303545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c69596a69add'
down_revision = '60dd37c838b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthlychargestwo', sa.Column('ptenant_id', sa.Integer(), nullable=True))
    op.drop_constraint('monthlychargestwo_tenant_id_fkey', 'monthlychargestwo', type_='foreignkey')
    op.create_foreign_key(None, 'monthlychargestwo', 'permanenttenants', ['ptenant_id'], ['id'])
    op.drop_column('monthlychargestwo', 'tenant_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthlychargestwo', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'monthlychargestwo', type_='foreignkey')
    op.create_foreign_key('monthlychargestwo_tenant_id_fkey', 'monthlychargestwo', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('monthlychargestwo', 'ptenant_id')
    # ### end Alembic commands ###
