"""empty message

Revision ID: c8194d4bd210
Revises: 044b5ff8a3b0
Create Date: 2022-11-03 13:39:41.664273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8194d4bd210'
down_revision = '044b5ff8a3b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salesreps', sa.Column('email', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salesreps', 'email')
    # ### end Alembic commands ###
