"""empty message

Revision ID: c89458e24736
Revises: 60d8a83d1a3c
Create Date: 2023-02-23 04:49:02.434387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c89458e24736'
down_revision = '60d8a83d1a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('occupancy', sa.Column('checkin_date', sa.DateTime(), nullable=True))
    op.add_column('occupancy', sa.Column('days_extended', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('occupancy', 'days_extended')
    op.drop_column('occupancy', 'checkin_date')
    # ### end Alembic commands ###
