"""empty message

Revision ID: ca161d08ecd3
Revises: 849f9e84cbe6
Create Date: 2021-03-12 14:38:04.725041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca161d08ecd3'
down_revision = '849f9e84cbe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meterreadings', 'reading',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meterreadings', 'reading',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
