"""empty message

Revision ID: cec3aca2c41a
Revises: 2d053baa0077
Create Date: 2021-01-29 02:00:12.293260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cec3aca2c41a'
down_revision = '2d053baa0077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('accumulated_fine', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'accumulated_fine')
    # ### end Alembic commands ###
