"""empty message

Revision ID: d16af2ec6e7e
Revises: a989bcf59f0c
Create Date: 2023-02-23 22:51:28.500978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd16af2ec6e7e'
down_revision = 'a989bcf59f0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('property_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'property_type')
    # ### end Alembic commands ###
