"""empty message

Revision ID: d20298e82580
Revises: 
Create Date: 2023-09-27 17:58:59.957560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd20298e82580'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenantdeposits', sa.Column('balance_elecdep', sa.Float(), nullable=True))
    op.add_column('tenantdeposits', sa.Column('balance_otherdep', sa.Float(), nullable=True))
    op.add_column('tenantdeposits', sa.Column('balance_rentdep', sa.Float(), nullable=True))
    op.add_column('tenantdeposits', sa.Column('balance_waterdep', sa.Float(), nullable=True))
    op.add_column('tenantdeposits', sa.Column('paid_elecdep', sa.Float(), nullable=True))
    op.add_column('tenantdeposits', sa.Column('paid_otherdep', sa.Float(), nullable=True))
    op.add_column('tenantdeposits', sa.Column('paid_rentdep', sa.Float(), nullable=True))
    op.add_column('tenantdeposits', sa.Column('paid_waterdep', sa.Float(), nullable=True))
    op.add_column('tenantdeposits', sa.Column('total_paid', sa.Float(), nullable=True))
    op.drop_column('tenantdeposits', 'paid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenantdeposits', sa.Column('paid', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('tenantdeposits', 'total_paid')
    op.drop_column('tenantdeposits', 'paid_waterdep')
    op.drop_column('tenantdeposits', 'paid_rentdep')
    op.drop_column('tenantdeposits', 'paid_otherdep')
    op.drop_column('tenantdeposits', 'paid_elecdep')
    op.drop_column('tenantdeposits', 'balance_waterdep')
    op.drop_column('tenantdeposits', 'balance_rentdep')
    op.drop_column('tenantdeposits', 'balance_otherdep')
    op.drop_column('tenantdeposits', 'balance_elecdep')
    # ### end Alembic commands ###
