"""empty message

Revision ID: d24133aa09f4
Revises: 1bc570b3c82b
Create Date: 2022-01-24 16:37:38.208120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24133aa09f4'
down_revision = '1bc570b3c82b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('reminder_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'reminder_status')
    # ### end Alembic commands ###
