"""empty message

Revision ID: d396038d34cd
Revises: 464eecb7fe00
Create Date: 2023-05-26 10:31:10.519177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd396038d34cd'
down_revision = '464eecb7fe00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentmessages', sa.Column('sms_period', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sentmessages', 'sms_period')
    # ### end Alembic commands ###
