"""empty message

Revision ID: d585fc579b47
Revises: d396038d34cd
Create Date: 2023-08-28 15:11:53.189625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd585fc579b47'
down_revision = 'd396038d34cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('mpesa', sa.String(), nullable=True))
    op.add_column('apartments', sa.Column('receipt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'receipt')
    op.drop_column('apartments', 'mpesa')
    # ### end Alembic commands ###
