"""empty message

Revision ID: d588a9ceb6e7
Revises: c53949792c64
Create Date: 2021-07-06 20:31:54.519701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd588a9ceb6e7'
down_revision = 'c53949792c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientbills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('installation', sa.Float(), nullable=True),
    sa.Column('subscription', sa.Float(), nullable=True),
    sa.Column('text', sa.Float(), nullable=True),
    sa.Column('maintenance', sa.Float(), nullable=True),
    sa.Column('customization', sa.Float(), nullable=True),
    sa.Column('arrears', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('paid', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('pay_date', sa.DateTime(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('sms_invoice', sa.String(), nullable=True),
    sa.Column('email_invoice', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientpayments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('paymode', sa.String(), nullable=True),
    sa.Column('ref_number', sa.VARCHAR(), nullable=True),
    sa.Column('payment_name', sa.String(), nullable=True),
    sa.Column('charged_amount', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('pay_date', sa.DateTime(), nullable=True),
    sa.Column('pay_period', sa.DateTime(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('sms_status', sa.String(), nullable=True),
    sa.Column('email_status', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('companies', sa.Column('balance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'balance')
    op.drop_table('clientpayments')
    op.drop_table('clientbills')
    # ### end Alembic commands ###
