"""empty message

Revision ID: d67f2176b61e
Revises: b9a431b0e3f3
Create Date: 2024-06-07 21:07:02.606696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd67f2176b61e'
down_revision = 'b9a431b0e3f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('items', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'items', 'departments', ['department_id'], ['id'])
    op.alter_column('stocks', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stocks', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'department_id')
    op.drop_table('departments')
    # ### end Alembic commands ###
