"""empty message

Revision ID: d6dfe2cfa157
Revises: 5a6d6bf0f797
Create Date: 2022-08-25 17:38:11.809202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6dfe2cfa157'
down_revision = '5a6d6bf0f797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenantdeposits', sa.Column('apartment_id', sa.Integer(), nullable=True))
    op.add_column('tenantdeposits', sa.Column('house_id', sa.Integer(), nullable=True))
    op.drop_constraint('tenantdeposits_company_id_fkey', 'tenantdeposits', type_='foreignkey')
    op.create_foreign_key(None, 'tenantdeposits', 'apartments', ['apartment_id'], ['id'])
    op.create_foreign_key(None, 'tenantdeposits', 'houses', ['house_id'], ['id'])
    op.drop_column('tenantdeposits', 'company_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenantdeposits', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tenantdeposits', type_='foreignkey')
    op.drop_constraint(None, 'tenantdeposits', type_='foreignkey')
    op.create_foreign_key('tenantdeposits_company_id_fkey', 'tenantdeposits', 'companies', ['company_id'], ['id'])
    op.drop_column('tenantdeposits', 'house_id')
    op.drop_column('tenantdeposits', 'apartment_id')
    # ### end Alembic commands ###
