"""empty message

Revision ID: d7449a0e4b54
Revises: e91b5c87e2f3
Create Date: 2020-12-05 02:53:49.579436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7449a0e4b54'
down_revision = 'e91b5c87e2f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('email', sa.VARCHAR(), nullable=True))
    op.add_column('companies', sa.Column('mail_box', sa.VARCHAR(), nullable=True))
    op.add_column('companies', sa.Column('phone', sa.VARCHAR(), nullable=True))
    op.add_column('companies', sa.Column('street_address', sa.VARCHAR(), nullable=True))
    op.drop_column('companies', 'address')
    op.drop_column('companies', 'comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('companies', 'street_address')
    op.drop_column('companies', 'phone')
    op.drop_column('companies', 'mail_box')
    op.drop_column('companies', 'email')
    # ### end Alembic commands ###
