"""empty message

Revision ID: d91c7b5d322d
Revises: dfc32819f2d3
Create Date: 2021-02-08 13:34:47.691900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91c7b5d322d'
down_revision = 'dfc32819f2d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('garbage_collector', sa.VARCHAR(), nullable=True))
    op.add_column('apartments', sa.Column('garbage_collector_bank', sa.VARCHAR(), nullable=True))
    op.add_column('apartments', sa.Column('garbage_collector_bankacc', sa.VARCHAR(), nullable=True))
    op.drop_column('companies', 'garbage_collector_bankacc')
    op.drop_column('companies', 'garbage_collector_bank')
    op.drop_column('companies', 'garbage_collector')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('garbage_collector', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('garbage_collector_bank', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('garbage_collector_bankacc', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('apartments', 'garbage_collector_bankacc')
    op.drop_column('apartments', 'garbage_collector_bank')
    op.drop_column('apartments', 'garbage_collector')
    # ### end Alembic commands ###
