"""empty message

Revision ID: d966fefdd2a8
Revises: 9167fd25cf57
Create Date: 2023-11-22 14:55:57.544617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd966fefdd2a8'
down_revision = '9167fd25cf57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthlycharges', sa.Column('dep_journal', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monthlycharges', 'dep_journal')
    # ### end Alembic commands ###
