"""empty message

Revision ID: dbf718ce47c2
Revises: 4ff3d54662f3
Create Date: 2023-02-26 09:48:02.270747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf718ce47c2'
down_revision = '4ff3d54662f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthlycharges', sa.Column('invoice_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monthlycharges', 'invoice_date')
    # ### end Alembic commands ###
