"""empty message

Revision ID: dcc33a0e5ddb
Revises: 21fd64c94ab2
Create Date: 2022-04-11 06:48:24.514505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcc33a0e5ddb'
down_revision = '21fd64c94ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortcodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shortcode', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shortcodes')
    # ### end Alembic commands ###
