"""empty message

Revision ID: de1271e56130
Revises: bbbeaae3229b
Create Date: 2021-03-04 13:16:35.260416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de1271e56130'
down_revision = 'bbbeaae3229b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('commission', sa.Float(), nullable=True))
    op.drop_column('apartments', 'commssion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('commssion', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('apartments', 'commission')
    # ### end Alembic commands ###
