"""empty message

Revision ID: dfc32819f2d3
Revises: 6283310dc369
Create Date: 2021-02-08 11:30:17.993680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfc32819f2d3'
down_revision = '6283310dc369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('city', sa.VARCHAR(), nullable=True))
    op.add_column('companies', sa.Column('garbage_collector', sa.VARCHAR(), nullable=True))
    op.add_column('companies', sa.Column('garbage_collector_bank', sa.VARCHAR(), nullable=True))
    op.add_column('companies', sa.Column('garbage_collector_bankacc', sa.VARCHAR(), nullable=True))
    op.add_column('companies', sa.Column('region', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'region')
    op.drop_column('companies', 'garbage_collector_bankacc')
    op.drop_column('companies', 'garbage_collector_bank')
    op.drop_column('companies', 'garbage_collector')
    op.drop_column('companies', 'city')
    # ### end Alembic commands ###
