"""empty message

Revision ID: e0b0281f6e14
Revises: f0745aa779c9
Create Date: 2021-06-24 13:42:06.011828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0b0281f6e14'
down_revision = 'f0745aa779c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('sphone', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'sphone')
    # ### end Alembic commands ###
