"""empty message

Revision ID: e2139007d52c
Revises: a475d964a1a4
Create Date: 2021-12-20 13:52:10.176070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2139007d52c'
down_revision = 'a475d964a1a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('texttemplates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('txt', sa.VARCHAR(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('reminders_company_id_fkey', 'reminders', type_='foreignkey')
    op.drop_column('reminders', 'company_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reminders', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('reminders_company_id_fkey', 'reminders', 'apartments', ['company_id'], ['id'])
    op.drop_table('texttemplates')
    # ### end Alembic commands ###
