"""empty message

Revision ID: e233bffc70d6
Revises: d9785606339d
Create Date: 2022-06-20 10:31:23.883509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e233bffc70d6'
down_revision = 'd9785606339d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landlordremittances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=True),
    sa.Column('landlord', sa.VARCHAR(), nullable=True),
    sa.Column('ll_balbf', sa.Float(), nullable=True),
    sa.Column('t_balbf', sa.Float(), nullable=True),
    sa.Column('rent', sa.Float(), nullable=True),
    sa.Column('utilities', sa.Float(), nullable=True),
    sa.Column('expected', sa.Float(), nullable=True),
    sa.Column('actual', sa.Float(), nullable=True),
    sa.Column('rent_paid', sa.Float(), nullable=True),
    sa.Column('commision', sa.Float(), nullable=True),
    sa.Column('remitted', sa.Float(), nullable=True),
    sa.Column('ratio', sa.Float(), nullable=True),
    sa.Column('ll_balcf', sa.Float(), nullable=True),
    sa.Column('agent', sa.Float(), nullable=True),
    sa.Column('date_remitted', sa.DateTime(), nullable=True),
    sa.Column('period', sa.DateTime(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('landlordremittances')
    # ### end Alembic commands ###
