"""empty message

Revision ID: e29b259c7447
Revises: a50c2f7c1f79
Create Date: 2024-12-18 13:41:34.349380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29b259c7447'
down_revision = 'a50c2f7c1f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_requests', sa.Column('trail_id', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('trail_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'trail_id')
    op.drop_column('collection_requests', 'trail_id')
    # ### end Alembic commands ###
