"""empty message

Revision ID: e2c82c25b459
Revises: 52bc9acb199e
Create Date: 2023-01-20 11:46:16.328337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2c82c25b459'
down_revision = '52bc9acb199e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('softdelete', sa.Boolean(), nullable=True))
    op.drop_column('users', 'delete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('delete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'softdelete')
    # ### end Alembic commands ###
