"""empty message

Revision ID: e31e73169b28
Revises: f4f4262fc59f
Create Date: 2021-03-01 14:34:40.823659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e31e73169b28'
down_revision = 'f4f4262fc59f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('billing_period', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'billing_period')
    # ### end Alembic commands ###
