"""empty message

Revision ID: e3680118b745
Revises: 546fedaeefa7
Create Date: 2021-08-30 10:00:02.323235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3680118b745'
down_revision = '546fedaeefa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housecodes', sa.Column('servicerate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('housecodes', 'servicerate')
    # ### end Alembic commands ###
