"""empty message

Revision ID: e417db891397
Revises: 0e28b4f3def4
Create Date: 2021-09-08 16:33:41.592074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e417db891397'
down_revision = '0e28b4f3def4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthlycharges', sa.Column('fine_date', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monthlycharges', 'fine_date')
    # ### end Alembic commands ###
