"""empty message

Revision ID: e4c01de6aade
Revises: c69596a69add
Create Date: 2022-05-15 10:04:12.593801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c01de6aade'
down_revision = 'c69596a69add'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housecodes', sa.Column('listprice', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('housecodes', 'listprice')
    # ### end Alembic commands ###
