"""empty message

Revision ID: e4e008d43aff
Revises: d7449a0e4b54
Create Date: 2020-12-06 16:18:40.879606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4e008d43aff'
down_revision = 'd7449a0e4b54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allocations', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('allocations', sa.Column('cleared_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('allocations', 'cleared_by')
    op.drop_column('allocations', 'active')
    # ### end Alembic commands ###
