"""empty message

Revision ID: e4f7794d80d7
Revises: f769beb9ae7b
Create Date: 2025-08-31 11:34:21.065513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f7794d80d7'
down_revision = 'f769beb9ae7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stock_damages_item_id_fkey', 'stock_damages', type_='foreignkey')
    op.drop_column('stock_damages', 'quantity')
    op.drop_column('stock_damages', 'item_id')
    op.drop_column('stock_damages', 'approval_status')
    op.drop_column('stock_damages', 'approved_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_damages', sa.Column('approved_by', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stock_damages', sa.Column('approval_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stock_damages', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stock_damages', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('stock_damages_item_id_fkey', 'stock_damages', 'stockitems', ['item_id'], ['id'])
    # ### end Alembic commands ###
