"""empty message

Revision ID: e61461f83bf9
Revises: 023b0d455421
Create Date: 2020-11-17 07:16:47.650970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61461f83bf9'
down_revision = '023b0d455421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('billable', sa.Boolean(), nullable=True))
    op.add_column('tenants', sa.Column('arrears', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'arrears')
    op.drop_column('houses', 'billable')
    # ### end Alembic commands ###
