"""empty message

Revision ID: e91b5c87e2f3
Revises: 8c720801883c
Create Date: 2020-11-28 10:53:17.163920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e91b5c87e2f3'
down_revision = '8c720801883c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meterreadings', sa.Column('last_reading', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meterreadings', 'last_reading')
    # ### end Alembic commands ###
