"""empty message

Revision ID: e9b39607f71d
Revises: 3adf11494f2f
Create Date: 2022-07-05 08:37:43.951235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9b39607f71d'
down_revision = '3adf11494f2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permanenttenants', sa.Column('uid', sa.VARCHAR(), nullable=True))
    op.drop_column('permanenttenants', 'uniquenameid')
    op.add_column('tenants', sa.Column('uid', sa.VARCHAR(), nullable=True))
    op.drop_column('tenants', 'uniquenameid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('uniquenameid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tenants', 'uid')
    op.add_column('permanenttenants', sa.Column('uniquenameid', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('permanenttenants', 'uid')
    # ### end Alembic commands ###
