"""empty message

Revision ID: e9baea3c7798
Revises: 91a015969381
Create Date: 2021-01-11 22:50:40.012376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9baea3c7798'
down_revision = '91a015969381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('residency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'residency')
    # ### end Alembic commands ###
