"""empty message

Revision ID: ea8f9fef257d
Revises: 5b7d54ee31fd
Create Date: 2024-06-08 00:00:37.185073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea8f9fef257d'
down_revision = '5b7d54ee31fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stocks', 'closing_stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stocks', 'selling_price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stocks', 'selling_price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('stocks', 'closing_stock',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
