"""empty message

Revision ID: eace4e7a1659
Revises: ed7026a59bbc
Create Date: 2025-08-30 13:39:46.615150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eace4e7a1659'
down_revision = 'ed7026a59bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('damages', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('damages_user_by_fkey', 'damages', type_='foreignkey')
    op.create_foreign_key(None, 'damages', 'users', ['user_id'], ['id'])
    op.drop_column('damages', 'user_by')
    op.add_column('purchases', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('purchases_user_by_fkey', 'purchases', type_='foreignkey')
    op.create_foreign_key(None, 'purchases', 'users', ['user_id'], ['id'])
    op.drop_column('purchases', 'user_by')
    op.add_column('stock_transactions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('stock_transactions_user_by_fkey', 'stock_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'stock_transactions', 'users', ['user_id'], ['id'])
    op.drop_column('stock_transactions', 'user_by')
    op.add_column('stockexpenses', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('stockexpenses_user_by_fkey', 'stockexpenses', type_='foreignkey')
    op.create_foreign_key(None, 'stockexpenses', 'users', ['user_id'], ['id'])
    op.drop_column('stockexpenses', 'user_by')
    op.add_column('stockitems', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('stockitems_user_by_fkey', 'stockitems', type_='foreignkey')
    op.create_foreign_key(None, 'stockitems', 'users', ['user_id'], ['id'])
    op.drop_column('stockitems', 'user_by')
    op.add_column('stocksales', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('stocksales_user_by_fkey', 'stocksales', type_='foreignkey')
    op.create_foreign_key(None, 'stocksales', 'users', ['user_id'], ['id'])
    op.drop_column('stocksales', 'user_by')
    op.add_column('stocktakedbs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('stocktakedbs_user_by_fkey', 'stocktakedbs', type_='foreignkey')
    op.create_foreign_key(None, 'stocktakedbs', 'users', ['user_id'], ['id'])
    op.drop_column('stocktakedbs', 'user_by')
    op.add_column('suppliers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('suppliers_user_by_fkey', 'suppliers', type_='foreignkey')
    op.create_foreign_key(None, 'suppliers', 'users', ['user_id'], ['id'])
    op.drop_column('suppliers', 'user_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('user_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.create_foreign_key('suppliers_user_by_fkey', 'suppliers', 'users', ['user_by'], ['id'])
    op.drop_column('suppliers', 'user_id')
    op.add_column('stocktakedbs', sa.Column('user_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stocktakedbs', type_='foreignkey')
    op.create_foreign_key('stocktakedbs_user_by_fkey', 'stocktakedbs', 'users', ['user_by'], ['id'])
    op.drop_column('stocktakedbs', 'user_id')
    op.add_column('stocksales', sa.Column('user_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stocksales', type_='foreignkey')
    op.create_foreign_key('stocksales_user_by_fkey', 'stocksales', 'users', ['user_by'], ['id'])
    op.drop_column('stocksales', 'user_id')
    op.add_column('stockitems', sa.Column('user_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stockitems', type_='foreignkey')
    op.create_foreign_key('stockitems_user_by_fkey', 'stockitems', 'users', ['user_by'], ['id'])
    op.drop_column('stockitems', 'user_id')
    op.add_column('stockexpenses', sa.Column('user_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stockexpenses', type_='foreignkey')
    op.create_foreign_key('stockexpenses_user_by_fkey', 'stockexpenses', 'users', ['user_by'], ['id'])
    op.drop_column('stockexpenses', 'user_id')
    op.add_column('stock_transactions', sa.Column('user_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'stock_transactions', type_='foreignkey')
    op.create_foreign_key('stock_transactions_user_by_fkey', 'stock_transactions', 'users', ['user_by'], ['id'])
    op.drop_column('stock_transactions', 'user_id')
    op.add_column('purchases', sa.Column('user_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.create_foreign_key('purchases_user_by_fkey', 'purchases', 'users', ['user_by'], ['id'])
    op.drop_column('purchases', 'user_id')
    op.add_column('damages', sa.Column('user_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'damages', type_='foreignkey')
    op.create_foreign_key('damages_user_by_fkey', 'damages', 'users', ['user_by'], ['id'])
    op.drop_column('damages', 'user_id')
    # ### end Alembic commands ###
