"""empty message

Revision ID: ec12fa0b7258
Revises: c389592a9fa7
Create Date: 2023-02-23 05:07:03.311320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec12fa0b7258'
down_revision = 'c389592a9fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('agreed_rates', sa.Float(), nullable=True))
    op.add_column('tenants', sa.Column('invoiced', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'invoiced')
    op.drop_column('tenants', 'agreed_rates')
    # ### end Alembic commands ###
