"""empty message

Revision ID: ed39a3738305
Revises: d6dfe2cfa157
Create Date: 2022-08-26 11:50:50.576207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed39a3738305'
down_revision = 'd6dfe2cfa157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenantdeposits', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('tenantdeposits', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenantdeposits', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tenantdeposits', 'status')
    # ### end Alembic commands ###
