"""empty message

Revision ID: ed7026a59bbc
Revises: 4c2480b419df
Create Date: 2025-08-23 18:06:58.628850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7026a59bbc'
down_revision = '4c2480b419df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('damages', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('damages', sa.Column('user_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'damages', 'users', ['user_by'], ['id'])
    op.create_foreign_key(None, 'damages', 'companies', ['company_id'], ['id'])
    op.add_column('purchases', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('purchases', sa.Column('user_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'purchases', 'users', ['user_by'], ['id'])
    op.create_foreign_key(None, 'purchases', 'companies', ['company_id'], ['id'])
    op.add_column('stock_transactions', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('stock_transactions', sa.Column('user_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stock_transactions', 'users', ['user_by'], ['id'])
    op.create_foreign_key(None, 'stock_transactions', 'companies', ['company_id'], ['id'])
    op.add_column('stockexpenses', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('stockexpenses', sa.Column('user_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stockexpenses', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'stockexpenses', 'users', ['user_by'], ['id'])
    op.add_column('stockitems', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('stockitems', sa.Column('user_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stockitems', 'users', ['user_by'], ['id'])
    op.create_foreign_key(None, 'stockitems', 'companies', ['company_id'], ['id'])
    op.add_column('stocksales', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('stocksales', sa.Column('user_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stocksales', 'users', ['user_by'], ['id'])
    op.create_foreign_key(None, 'stocksales', 'companies', ['company_id'], ['id'])
    op.add_column('stocktakedbs', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('stocktakedbs', sa.Column('user_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stocktakedbs', 'users', ['user_by'], ['id'])
    op.create_foreign_key(None, 'stocktakedbs', 'companies', ['company_id'], ['id'])
    op.add_column('suppliers', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('suppliers', sa.Column('user_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'suppliers', 'users', ['user_by'], ['id'])
    op.create_foreign_key(None, 'suppliers', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_column('suppliers', 'user_by')
    op.drop_column('suppliers', 'company_id')
    op.drop_constraint(None, 'stocktakedbs', type_='foreignkey')
    op.drop_constraint(None, 'stocktakedbs', type_='foreignkey')
    op.drop_column('stocktakedbs', 'user_by')
    op.drop_column('stocktakedbs', 'company_id')
    op.drop_constraint(None, 'stocksales', type_='foreignkey')
    op.drop_constraint(None, 'stocksales', type_='foreignkey')
    op.drop_column('stocksales', 'user_by')
    op.drop_column('stocksales', 'company_id')
    op.drop_constraint(None, 'stockitems', type_='foreignkey')
    op.drop_constraint(None, 'stockitems', type_='foreignkey')
    op.drop_column('stockitems', 'user_by')
    op.drop_column('stockitems', 'company_id')
    op.drop_constraint(None, 'stockexpenses', type_='foreignkey')
    op.drop_constraint(None, 'stockexpenses', type_='foreignkey')
    op.drop_column('stockexpenses', 'user_by')
    op.drop_column('stockexpenses', 'company_id')
    op.drop_constraint(None, 'stock_transactions', type_='foreignkey')
    op.drop_constraint(None, 'stock_transactions', type_='foreignkey')
    op.drop_column('stock_transactions', 'user_by')
    op.drop_column('stock_transactions', 'company_id')
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_column('purchases', 'user_by')
    op.drop_column('purchases', 'company_id')
    op.drop_constraint(None, 'damages', type_='foreignkey')
    op.drop_constraint(None, 'damages', type_='foreignkey')
    op.drop_column('damages', 'user_by')
    op.drop_column('damages', 'company_id')
    # ### end Alembic commands ###
