"""empty message

Revision ID: ee17db731714
Revises: 7f3773c72f36
Create Date: 2022-04-12 17:20:09.608172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee17db731714'
down_revision = '7f3773c72f36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monthlycharges', sa.Column('ptenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'monthlycharges', 'permanenttenants', ['ptenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'monthlycharges', type_='foreignkey')
    op.drop_column('monthlycharges', 'ptenant_id')
    # ### end Alembic commands ###
