"""empty message

Revision ID: ee458a665154
Revises: 8a401e4cec0e
Create Date: 2022-03-11 10:35:29.277414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee458a665154'
down_revision = '8a401e4cec0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('sms_provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'sms_provider')
    # ### end Alembic commands ###
