"""empty message

Revision ID: ee867eb15512
Revises: b79b643d46a9
Create Date: 2024-12-19 15:11:00.463219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee867eb15512'
down_revision = 'b79b643d46a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounttrails', sa.Column('collected_by', sa.Integer(), nullable=True))
    op.add_column('accounttrails', sa.Column('posted_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounttrails', 'posted_by')
    op.drop_column('accounttrails', 'collected_by')
    # ### end Alembic commands ###
