"""empty message

Revision ID: f04a062bc927
Revises: 113e5b6823a7
Create Date: 2025-12-28 16:49:06.324043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f04a062bc927'
down_revision = '113e5b6823a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('submissions_tenant_id_fkey', 'submissions', type_='foreignkey')
    op.drop_constraint('submissions_house_id_fkey', 'submissions', type_='foreignkey')
    op.drop_column('submissions', 'house_id')
    op.drop_column('submissions', 'tenant_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('house_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('submissions_house_id_fkey', 'submissions', 'houses', ['house_id'], ['id'])
    op.create_foreign_key('submissions_tenant_id_fkey', 'submissions', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###
