"""empty message

Revision ID: f0745aa779c9
Revises: 268d40bd56fa
Create Date: 2021-06-10 11:33:33.391325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0745aa779c9'
down_revision = '268d40bd56fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('landlord_bank', sa.VARCHAR(), nullable=True))
    op.add_column('apartments', sa.Column('landlord_bank_two', sa.VARCHAR(), nullable=True))
    op.add_column('apartments', sa.Column('landlord_bankacc', sa.VARCHAR(), nullable=True))
    op.add_column('apartments', sa.Column('landlord_bankacc_two', sa.VARCHAR(), nullable=True))
    op.add_column('apartments', sa.Column('landlord_bankaccname', sa.VARCHAR(), nullable=True))
    op.add_column('apartments', sa.Column('landlord_bankaccname_two', sa.VARCHAR(), nullable=True))
    op.add_column('apartments', sa.Column('payment_bankaccname', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'payment_bankaccname')
    op.drop_column('apartments', 'landlord_bankaccname_two')
    op.drop_column('apartments', 'landlord_bankaccname')
    op.drop_column('apartments', 'landlord_bankacc_two')
    op.drop_column('apartments', 'landlord_bankacc')
    op.drop_column('apartments', 'landlord_bank_two')
    op.drop_column('apartments', 'landlord_bank')
    # ### end Alembic commands ###
