"""empty message

Revision ID: f34d7e100229
Revises: 37a6b7b37965
Create Date: 2021-04-06 13:11:03.153083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34d7e100229'
down_revision = '37a6b7b37965'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('int_commission', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'int_commission')
    # ### end Alembic commands ###
