"""empty message

Revision ID: f43318232ee3
Revises: ab9a3e0fbe04
Create Date: 2022-05-15 08:54:44.273639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f43318232ee3'
down_revision = 'ab9a3e0fbe04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthlychargestwo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('deposit', sa.Float(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('plans', sa.Integer(), nullable=True),
    sa.Column('plan_counter', sa.Integer(), nullable=True),
    sa.Column('number_instalments', sa.Integer(), nullable=True),
    sa.Column('remaining_number_instalments', sa.Integer(), nullable=True),
    sa.Column('payment_stage', sa.Integer(), nullable=True),
    sa.Column('instalment', sa.Float(), nullable=True),
    sa.Column('bbf', sa.Float(), nullable=True),
    sa.Column('bill', sa.Float(), nullable=True),
    sa.Column('paid', sa.Float(), nullable=True),
    sa.Column('bcf', sa.Float(), nullable=True),
    sa.Column('cpaid', sa.Float(), nullable=True),
    sa.Column('cbal', sa.Float(), nullable=True),
    sa.Column('sms_invoice', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('pay_date', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rep_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.ForeignKeyConstraint(['rep_id'], ['salesreps.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monthlychargestwo')
    # ### end Alembic commands ###
