"""empty message

Revision ID: f4f4262fc59f
Revises: 0976650b5bae
Create Date: 2021-02-27 20:56:24.709380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f4262fc59f'
down_revision = '0976650b5bae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('agreement_fee', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('agreement', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('deposit', sa.Float(), nullable=True))
    op.add_column('monthlycharges', sa.Column('pay_date', sa.DateTime(), nullable=True))
    op.add_column('payments', sa.Column('pay_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'pay_date')
    op.drop_column('monthlycharges', 'pay_date')
    op.drop_column('monthlycharges', 'deposit')
    op.drop_column('monthlycharges', 'agreement')
    op.drop_column('apartments', 'agreement_fee')
    # ### end Alembic commands ###
