"""empty message

Revision ID: f6a181b3a9e1
Revises: 9c805c093179
Create Date: 2023-02-23 05:02:11.349615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6a181b3a9e1'
down_revision = '9c805c093179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permanenttenants', sa.Column('randid', sa.VARCHAR(), nullable=True))
    op.add_column('tenants', sa.Column('randid', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'randid')
    op.drop_column('permanenttenants', 'randid')
    # ### end Alembic commands ###
