"""empty message

Revision ID: f6f9e7b44590
Revises: d585fc579b47
Create Date: 2023-08-28 15:25:56.768661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6f9e7b44590'
down_revision = 'd585fc579b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('mpesa', sa.String(), nullable=True))
    op.add_column('apartments', sa.Column('receipt', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'receipt')
    op.drop_column('apartments', 'mpesa')
    # ### end Alembic commands ###
