"""empty message

Revision ID: f769beb9ae7b
Revises: eace4e7a1659
Create Date: 2025-08-30 23:49:26.250299

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f769beb9ae7b'
down_revision = 'eace4e7a1659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_takes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('stock_take_date', sa.DateTime(), nullable=True),
    sa.Column('expected_quantity', sa.Integer(), nullable=True),
    sa.Column('actual_quantity', sa.Integer(), nullable=True),
    sa.Column('discrepancy_notes', sa.VARCHAR(), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['stockitems.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_damages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('damage_date', sa.DateTime(), nullable=True),
    sa.Column('damage_reason', sa.VARCHAR(), nullable=True),
    sa.Column('approval_status', sa.String(), nullable=True),
    sa.Column('approved_by', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('stock_transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['stockitems.id'], ),
    sa.ForeignKeyConstraint(['stock_transaction_id'], ['stock_transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_expenses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('expense_date', sa.DateTime(), nullable=True),
    sa.Column('approval_status', sa.String(), nullable=True),
    sa.Column('approved_by', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('state', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('stock_transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['stock_transaction_id'], ['stock_transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('stockexpenses')
    op.drop_table('stocktakedbs')
    op.drop_table('damages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('damages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('damage_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('damage_reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('approval_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('stock_transaction_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='damages_company_id_fkey'),
    sa.ForeignKeyConstraint(['item_id'], ['stockitems.id'], name='damages_item_id_fkey'),
    sa.ForeignKeyConstraint(['stock_transaction_id'], ['stock_transactions.id'], name='damages_stock_transaction_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='damages_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='damages_pkey')
    )
    op.create_table('stocktakedbs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stock_take_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expected_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actual_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('discrepancy_notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='stocktakedbs_company_id_fkey'),
    sa.ForeignKeyConstraint(['item_id'], ['stockitems.id'], name='stocktakedbs_item_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='stocktakedbs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stocktakedbs_pkey')
    )
    op.create_table('stockexpenses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('expense_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('approval_status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('approved_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('stock_transaction_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='stockexpenses_company_id_fkey'),
    sa.ForeignKeyConstraint(['stock_transaction_id'], ['stock_transactions.id'], name='stockexpenses_stock_transaction_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='stockexpenses_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stockexpenses_pkey')
    )
    op.drop_table('stock_expenses')
    op.drop_table('stock_damages')
    op.drop_table('stock_takes')
    # ### end Alembic commands ###
