"""empty message

Revision ID: f7d3c06d9323
Revises: e233bffc70d6
Create Date: 2022-06-20 11:35:23.620974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7d3c06d9323'
down_revision = 'e233bffc70d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landlordremittances', sa.Column('apartment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'landlordremittances', 'apartments', ['apartment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'landlordremittances', type_='foreignkey')
    op.drop_column('landlordremittances', 'apartment_id')
    # ### end Alembic commands ###
