"""empty message

Revision ID: f9b6b9e9f7de
Revises: 10c10181b71f
Create Date: 2020-12-14 20:31:56.873173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9b6b9e9f7de'
down_revision = '10c10181b71f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('housecodes_charge_type_id_fkey', 'housecodes', type_='foreignkey')
    op.drop_column('housecodes', 'charge_type_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housecodes', sa.Column('charge_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('housecodes_charge_type_id_fkey', 'housecodes', 'chargetypes', ['charge_type_id'], ['id'])
    # ### end Alembic commands ###
