"""empty message

Revision ID: fbca1ffe873d
Revises: 39e254b4c08e
Create Date: 2025-09-20 20:18:27.888761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbca1ffe873d'
down_revision = '39e254b4c08e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stockitems', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stockitems', 'updated_at')
    # ### end Alembic commands ###
