"""empty message

Revision ID: fc446deccc19
Revises: f9b6b9e9f7de
Create Date: 2020-12-28 18:24:13.521964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc446deccc19'
down_revision = 'f9b6b9e9f7de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housecodes', sa.Column('elecdep', sa.Float(), nullable=True))
    op.add_column('housecodes', sa.Column('waterdep', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('housecodes', 'waterdep')
    op.drop_column('housecodes', 'elecdep')
    # ### end Alembic commands ###
