"""empty message

Revision ID: fca85795b319
Revises: 36dcadc90947
Create Date: 2021-04-09 15:12:56.107539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fca85795b319'
down_revision = '36dcadc90947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('email_status', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('sms_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'sms_status')
    op.drop_column('payments', 'email_status')
    # ### end Alembic commands ###
