"""empty message

Revision ID: fcf44e4d5722
Revises: b814ae8de5f2
Create Date: 2021-07-03 19:46:06.727746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcf44e4d5722'
down_revision = 'b814ae8de5f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('housecodes', sa.Column('createdby', sa.Integer(), nullable=True))
    op.add_column('housecodes', sa.Column('modifiedby', sa.Integer(), nullable=True))
    op.add_column('housecodes', sa.Column('modifiedon', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'housecodes', 'users', ['createdby'], ['id'])
    op.create_foreign_key(None, 'housecodes', 'users', ['modifiedby'], ['id'])
    op.add_column('meterreadings', sa.Column('createdby', sa.Integer(), nullable=True))
    op.add_column('meterreadings', sa.Column('modifiedby', sa.Integer(), nullable=True))
    op.add_column('meterreadings', sa.Column('modifiedon', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'meterreadings', 'users', ['modifiedby'], ['id'])
    op.create_foreign_key(None, 'meterreadings', 'users', ['createdby'], ['id'])
    op.add_column('payments', sa.Column('createdby', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('modifiedby', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('modifiedon', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'payments', 'users', ['modifiedby'], ['id'])
    op.create_foreign_key(None, 'payments', 'users', ['createdby'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'modifiedon')
    op.drop_column('payments', 'modifiedby')
    op.drop_column('payments', 'createdby')
    op.drop_constraint(None, 'meterreadings', type_='foreignkey')
    op.drop_constraint(None, 'meterreadings', type_='foreignkey')
    op.drop_column('meterreadings', 'modifiedon')
    op.drop_column('meterreadings', 'modifiedby')
    op.drop_column('meterreadings', 'createdby')
    op.drop_constraint(None, 'housecodes', type_='foreignkey')
    op.drop_constraint(None, 'housecodes', type_='foreignkey')
    op.drop_column('housecodes', 'modifiedon')
    op.drop_column('housecodes', 'modifiedby')
    op.drop_column('housecodes', 'createdby')
    # ### end Alembic commands ###
