"""empty message

Revision ID: fda188fdb844
Revises: e9b39607f71d
Create Date: 2022-07-06 11:31:57.610304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fda188fdb844'
down_revision = 'e9b39607f71d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymentschedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_date', sa.DateTime(), nullable=True),
    sa.Column('schedule_name', sa.String(), nullable=True),
    sa.Column('arrears', sa.Float(), nullable=True),
    sa.Column('schedule_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('paid', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('pay_date', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('apartment_id', sa.Integer(), nullable=True),
    sa.Column('house_id', sa.Integer(), nullable=True),
    sa.Column('ptenant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.ForeignKeyConstraint(['ptenant_id'], ['permanenttenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('monthlychargestwo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthlychargestwo',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('total_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('deposit', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('plans', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('plan_counter', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('number_instalments', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('remaining_number_instalments', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payment_stage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('instalment', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bbf', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bill', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('paid', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bcf', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cpaid', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cbal', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sms_invoice', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('pay_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('apartment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('house_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rep_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ptenant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.id'], name='monthlychargestwo_apartment_id_fkey'),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], name='monthlychargestwo_house_id_fkey'),
    sa.ForeignKeyConstraint(['ptenant_id'], ['permanenttenants.id'], name='monthlychargestwo_ptenant_id_fkey'),
    sa.ForeignKeyConstraint(['rep_id'], ['salesreps.id'], name='monthlychargestwo_rep_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='monthlychargestwo_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='monthlychargestwo_pkey')
    )
    op.drop_table('paymentschedules')
    # ### end Alembic commands ###
