"""empty message

Revision ID: ff1f2ccbf8fd
Revises: e4f7794d80d7
Create Date: 2025-08-31 16:12:56.929952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff1f2ccbf8fd'
down_revision = 'e4f7794d80d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stock_expenses_stock_transaction_id_fkey', 'stock_expenses', type_='foreignkey')
    op.drop_column('stock_expenses', 'stock_transaction_id')
    op.add_column('stock_takes', sa.Column('notes', sa.VARCHAR(), nullable=True))
    op.add_column('stock_takes', sa.Column('stock_take_type', sa.VARCHAR(), nullable=True))
    op.drop_column('stock_takes', 'expected_quantity')
    op.drop_column('stock_takes', 'actual_quantity')
    op.drop_column('stock_takes', 'discrepancy_notes')
    op.add_column('stock_transactions', sa.Column('stock_take_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stock_transactions', 'stock_takes', ['stock_take_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_transactions', type_='foreignkey')
    op.drop_column('stock_transactions', 'stock_take_id')
    op.add_column('stock_takes', sa.Column('discrepancy_notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('stock_takes', sa.Column('actual_quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stock_takes', sa.Column('expected_quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('stock_takes', 'stock_take_type')
    op.drop_column('stock_takes', 'notes')
    op.add_column('stock_expenses', sa.Column('stock_transaction_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('stock_expenses_stock_transaction_id_fkey', 'stock_expenses', 'stock_transactions', ['stock_transaction_id'], ['id'])
    # ### end Alembic commands ###
